<table>
        <td>
        <td><img src="https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/logo_ECI.png" width="400"/></td>
        <td>&nbsp;</td>
        <td>
            <h1 style="font-size:200%;color:blue;text-align:center">    <FONT COLOR="blue"> DataFrames </p> Estructuras de Control</p> if-for-while </FONT>         </h1></td>         
        <td>
            <tp><p style="font-size:99%;text-align:center">Diplomado Ciencia de Datos </p></tp>
            <tp><p style="font-size:115%;text-align:center">2026-2</p></tp>
            <tp><p style="font-size:115%;text-align:center">Prof. Fabián Sánchez</p></tp>
        </td>
    </tr>
</table>

# <FONT SIZE=5 COLOR="purple"> 1. Estructuras de Control </FONT>

Una **estructura de control** es un concepto básico de la programación (especialmente en el campo de la ciencias de la computación) que sirve para decidir cómo se ejecutan las instrucciones de un programa.

En pocas palabras:

- Indica en qué orden se ejecuta el código, si se repite o si se toman decisiones.

- Estas estructuras de permite modificar el orden en el cual se ejecutan las instrucciones de un algoritmo.

##  <FONT SIZE=5 COLOR="green"> Tipos de estructuras de control </FONT>

**1. Secuencial**

Es la forma más simple: las instrucciones se ejecutan una tras otra, en orden.

```python
leer número
sumar 5
mostrar resultado
```

**2. Condicional (decisión)**

Permite que el programa tome decisiones dependiendo de una condición.

```python
si (edad >= 18)
    mostrar "Eres mayor de edad"
si no
    mostrar "Eres menor de edad"
```

**3. Repetitiva (bucles)**

Sirve para repetir instrucciones varias veces.

```python
mientras (contador < 5)
    mostrar contador
    contador = contador + 1
```

**¿Para qué sirven?**

Las estructuras de control permiten que un programa:

- Tome decisiones
- Repita acciones
- Controle el flujo del programa

Sin ellas, los programas solo ejecutarían instrucciones de forma lineal, sin lógica.

Ejemplo

```python
edad_maria = 56
edad_alberto = 47

# Si María es mayor en edad que Alberto entonces:
if (edad_maria > edad_alberto):
  print('María tiene más años que Alberto.')
# De lo contrario:
else:
  print('Alberto tiene mas años que María.')

```

# <FONT SIZE=5 COLOR="purple"> 2. Condicional if</FONT>

El condicional **if** es una estructura de control que permite que un programa tome decisiones. Evalúa una condición y, si esta es verdadera, ejecuta un bloque de instrucciones. Si la condición es falsa, ese bloque no se ejecuta (o se ejecuta otro bloque si se utiliza **else**).

```python
if condición:
    instrucciones
```

Ejemplo

```python
edad = 20
if edad >= 18:
    print("Eres mayor de edad")
```

**Uso de else**

Cuando queremos ejecutar una acción diferente si la condición es falsa, utilizamos *else:*

```python
edad = 16

if edad >= 18:
    print("Eres mayor de edad")
else:
    print("Eres menor de edad")
```

Las estructuras condicionales permiten que los programas reaccionen a diferentes situaciones y tomen decisiones de manera automática. Gracias al **if**, es posible validar datos, controlar accesos, comparar valores y adaptar el comportamiento del programa según las condiciones que se presenten.

**Ejemplo 1**

In [2]:
a = 3
if a > 8:
  print("Hola")
else:
  print("Adiós")

Adiós

**Ejemplo 2**

In [3]:
a = 15
b = 10
if a > b:
    print("a es mayor que b")

a es mayor que b

In [4]:
a = 15
b = 10
if a > b:
    print(f"{a} es mayor que {b}")

15 es mayor que 10

**Ejemplo 3**

In [5]:
edad = 20
if edad >= 18:
    print("Eres mayor de edad")
else:
    print("Eres menor de edad")

Eres mayor de edad

**Ejemplo 4**

In [ ]:
temperatura = 25

if temperatura > 20:
    print("Clima agradable")
else:
    print("Hace frío")

Podemos combinar las instrucciones con funciones

**Ejemplo 5**

In [9]:
def clima(temperatura):
    if temperatura > 20:
        print("El clima es agradable")
    else:
        print("uyyy! Hace frío")

In [10]:
clima(50)

El clima es agradable

In [15]:
def clima2(temperatura):
    if temperatura > 20:
        print("Clima agradable")
    elif temperatura == 20:
        print("Clima normal")
    else:
        print("Hace frío")

In [16]:
clima2(-20)

Hace frío

In [17]:
clima2(100)

Clima agradable

In [18]:
clima2()

TypeError: clima2() missing 1 required positional argument: 'temperatura'

In [19]:
import pandas as pd
import numpy  as np

In [20]:
# cargamos los datos: apartamentos
aptos = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/master/apartamentos.csv")
aptos.head()

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,1,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,2,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,3,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,4,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,5,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

**Ejemplo 6**

In [22]:
def tamano(metros2):
  if metros2 >= 80:
    return "el apartamento es grande"
  else:
    return "el apartamento es pequeño"

In [23]:
tamano(60)

'el apartamento es pequeño'

In [24]:
tamano(90)

'el apartamento es grande'

**¿Cómo aplicar una función a todos los elementos de la variable?**

In [25]:
# se utiliza la función apply
aptos["Tamano"] = aptos.mt2.apply(tamano)

In [26]:
aptos.head()

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado,Tamano
0,1,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no,el apartamento es pequeño
1,2,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si,el apartamento es pequeño
2,3,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no,el apartamento es pequeño
3,4,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no,el apartamento es pequeño
4,5,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si,el apartamento es grande

Veamos algunos ejemplos con datos

In [29]:
aptos.precio.mean()

np.float64(317.7627391930836)

In [30]:
#Ejemplo 1
if aptos.precio.mean() > 400:
    print("El apartamento tiene un precio alto")
else:
    print("El apartamento tiene un precio bajo")

El apartamento tiene un precio bajo

**Ejemplo**

In [31]:
def clasificar(precio):
    if precio >= 400:
        return 'El apartamento es caro'
    elif precio < 400 and precio > 200:
        return 'El apartamento está bien'
    else:
        return 'El apartamento es barato'

In [32]:
aptos["clasificacion"] = aptos.precio.apply(clasificar)

In [33]:
aptos.head()

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado,Tamano,clasificacion
0,1,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no,el apartamento es pequeño,El apartamento es barato
1,2,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si,el apartamento es pequeño,El apartamento es barato
2,3,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no,el apartamento es pequeño,El apartamento es barato
3,4,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no,el apartamento es pequeño,El apartamento es barato
4,5,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si,el apartamento es grande,El apartamento es barato

In [ ]:
# Ejemplo 3
def aplicar_descuento(valor):
  if valor == "no":
    return "sin descuento"
  elif valor == "si":
    return "con descuento"
  else:
    return "no sé"

aptos["descuentos"] = aptos.terminado.apply(aplicar_descuento)

In [ ]:
aptos.head()

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado,clasificacion,Tamano,descuentos
0,1,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no,El apartamento es barato,pequeño,sin descuento
1,2,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si,El apartamento es barato,pequeño,con descuento
2,3,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no,El apartamento es barato,pequeño,sin descuento
3,4,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no,El apartamento es barato,pequeño,sin descuento
4,5,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si,El apartamento es barato,grande,con descuento

In [ ]:
aptos.terminado.apply(aplicar_descuento)

Veamos otros ejemplos

In [34]:
# ejemplo
# tipo de datos columnas
aptos.precio.dtype == "float64"

True

In [35]:
# ejemplo
if aptos.terminado.dtype == "object":
  print("Esta es una variable categórica")

Esta es una variable categórica

In [37]:
# ejemplo
if aptos.terminado.dtype == "object":
  print("Esta es una variable categórica")
  print(aptos.terminado.unique())
else:
  print("Esta es una variable numérica")

Esta es una variable categórica
['no' 'si']

También se le podría incluir otra condición a evaluar (puede ser de conjunción, disyunción y/o negación).


```python
edad_maria = 56
edad_alberto = 47
altura_maria = 1.56
altura_alberto = 1.70

# Si María es mayor en edad que Alberto entonces:
if (edad_maria > edad_alberto):
  print('María tiene más años que Alberto')
  
  if (altura_maria > altura_alberto):
    print('Adicionalmente, es más alta que Alberto.')
  
  else:
    print('Sin embargo Alberto es más alto.')
  
# De lo contrario:
else:
  print('Alberto tiene mas años que María.')
  
  if (altura_maria < altura_alberto):
    print('Adicionalmente, es más alto que María.')
  
  else:
    print('Sin embargo María es más alta.')

```

# <FONT SIZE=5 COLOR="purple"> 2. Cíclica *for* </FONT>

El ciclo *for* es una estructura de control repetitiva que permite ejecutar un bloque de código varias veces. Se utiliza cuando conocemos cuántas veces queremos repetir una acción o cuando queremos recorrer los elementos de una colección (lista, cadena, DataFrame, etc.).

```python
for variable in secuencia:
    instrucciones
```

In [38]:
# ejemplo 1
frutas = ['manzana', 'pera', 'uva']

for fruta in frutas:
    print(fruta)

manzana
pera
uva

In [39]:
# ejemplo 2
for i in range(10,16):
    print(i**2)

100
121
144
169
196
225

In [40]:
# ejemplo 3
suma = 0
for i in range(1, 6):
    suma = suma + i
    print(suma)

1
3
6
10
15

In [41]:
# ejemplo 3
suma = 0
for i in range(1, 6):
    suma = suma + i

print(suma)

15

In [42]:
# ejemplo 4
for letra in "Python":
    print(letra)

P
y
t
h
o
n

In [43]:
# ejemplo 4
for letra in ["Python", "R" , "SAS", 78]:
    print(letra)

Python
R
SAS
78

In [44]:
for columnas in aptos.columns:
  print(f"{columnas}")  # f-string

Unnamed: 0
precio
mt2
ubicacion
estrato
alcobas
banos
balcon
parqueadero
administracion
avaluo
terminado
Tamano
clasificacion

In [45]:
aptos.columns

Index(['Unnamed: 0', 'precio', 'mt2', 'ubicacion', 'estrato', 'alcobas',
       'banos', 'balcon', 'parqueadero', 'administracion', 'avaluo',
       'terminado', 'Tamano', 'clasificacion'],
      dtype='object')

In [46]:
# ejemplo 5
for columna in aptos.columns:
    print(f"{columna}: {aptos[columna].dtype}")

Unnamed: 0: int64
precio: float64
mt2: float64
ubicacion: object
estrato: int64
alcobas: int64
banos: int64
balcon: object
parqueadero: object
administracion: float64
avaluo: float64
terminado: object
Tamano: object
clasificacion: object

In [48]:
# ejemplo 5
for columna in aptos.columns:
  if aptos[columna].dtype == "object":
    print(f"{columna}: {aptos[columna].unique()}")

ubicacion: ['norte' 'occidente' 'poblado' 'aburra sur' 'belen guayabal' 'centro'
 'laureles']
balcon: ['si' 'no']
parqueadero: ['si' 'no']
terminado: ['no' 'si']
Tamano: ['el apartamento es pequeño' 'el apartamento es grande']
clasificacion: ['El apartamento es barato' 'El apartamento está bien'
 'El apartamento es caro']

Carguemos otros datos

In [53]:
# cargamos los datos crédito
credito = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/credict_para_limpiar.csv")
credito.head()

,Trajeta,Reportes Negativos,Edad,Ingreso,Proporcion de Gasto,Gasto,Propietario de Vivienda,Trabajor Independiente,Dependientes,Meses de Historial,Tarjetas Principales,Cuentas Activas
0,yes,0,37.66667,4.5200,0.033270,124.983300,yes,no,3,54,1,12.0
1,yes,0,33.25,2.4200,0.005217,9.854167,no,no,3,34,1,13.0
2,yes,0,33.66667,4.5000,0.004156,15.000000,yes,no,4,5o,1,5.0
3,yes,0,30.5,2.5400,0.065214,137.869200,no,no,0,25,1,7.0
4,yes,0,32.16667,9.7867,0.067051,546.503300,yes,no,2,64,1,5.0

In [54]:
# ejemplo 6
for columna in credito.columns:
    nulos = credito[columna].isnull().sum()
    print(f"{columna}: {nulos} valores nulos")

Trajeta: 0 valores nulos
Reportes Negativos: 0 valores nulos
Edad: 2 valores nulos
Ingreso: 1 valores nulos
Proporcion de Gasto: 1 valores nulos
Gasto: 0 valores nulos
Propietario de Vivienda: 1 valores nulos
Trabajor Independiente: 2 valores nulos
Dependientes: 0 valores nulos
Meses de Historial: 5 valores nulos
Tarjetas Principales: 0 valores nulos
Cuentas Activas: 1 valores nulos

In [55]:
aptos.columns

Index(['Unnamed: 0', 'precio', 'mt2', 'ubicacion', 'estrato', 'alcobas',
       'banos', 'balcon', 'parqueadero', 'administracion', 'avaluo',
       'terminado', 'Tamano', 'clasificacion'],
      dtype='object')

In [56]:
aptos.select_dtypes(include='object').columns

Index(['ubicacion', 'balcon', 'parqueadero', 'terminado', 'Tamano',
       'clasificacion'],
      dtype='object')

In [57]:
# ejemplo 7
for columna in aptos.select_dtypes(include='object').columns:
    print(f"\n{columna}")
    print(aptos[columna].unique())

ubicacion
['norte' 'occidente' 'poblado' 'aburra sur' 'belen guayabal' 'centro'
 'laureles']

balcon
['si' 'no']

parqueadero
['si' 'no']

terminado
['no' 'si']

Tamano
['el apartamento es pequeño' 'el apartamento es grande']

clasificacion
['El apartamento es barato' 'El apartamento está bien'
 'El apartamento es caro']

In [58]:
for columna in aptos.select_dtypes(include='object').columns:
    print(f"\n{columna}\n")
    display(aptos[columna].value_counts())

ubicacion

ubicacion
poblado           268
aburra sur        169
laureles           73
occidente          69
belen guayabal     67
centro             38
norte              10
Name: count, dtype: int64

balcon

balcon
si    509
no    185
Name: count, dtype: int64

parqueadero

parqueadero
si    568
no    126
Name: count, dtype: int64

terminado

terminado
si    592
no    102
Name: count, dtype: int64

Tamano

Tamano
el apartamento es grande     464
el apartamento es pequeño    230
Name: count, dtype: int64

clasificacion

clasificacion
El apartamento está bien    278
El apartamento es barato    259
El apartamento es caro      157
Name: count, dtype: int64

In [ ]:
credito.columns

Index(['Trajeta', 'Reportes Negativos', 'Edad', 'Ingreso',
       'Proporcion de Gasto', 'Gasto', 'Propietario de Vivienda',
       'Trabajor Independiente', 'Dependientes', 'Meses de Historial',
       'Tarjetas Principales', 'Cuentas Activas'],
      dtype='object')

In [60]:
for columna in credito.columns:
    porcentaje = credito[columna].isna().sum() / len(credito[columna]) * 100
    if porcentaje > 0:
        print(f"{columna}: {porcentaje:.4f}% de nulos")

Edad: 0.1516% de nulos
Ingreso: 0.0758% de nulos
Proporcion de Gasto: 0.0758% de nulos
Propietario de Vivienda: 0.0758% de nulos
Trabajor Independiente: 0.1516% de nulos
Meses de Historial: 0.3791% de nulos
Cuentas Activas: 0.0758% de nulos

In [61]:
# datos atípicos
for columna in aptos.select_dtypes(include='number').columns:

    q1 = aptos[columna].quantile(0.25)
    q3 = aptos[columna].quantile(0.75)
    iqr = q3 - q1

    outliers = aptos[
        (aptos[columna] < q1 - 1.5*iqr) |
        (aptos[columna] > q3 + 1.5*iqr)
    ]

    print(f"{columna}: {len(outliers)} outliers")

Unnamed: 0: 0 outliers
precio: 51 outliers
mt2: 58 outliers
estrato: 0 outliers
alcobas: 221 outliers
banos: 9 outliers
administracion: 22 outliers
avaluo: 48 outliers

In [ ]:
import matplotlib.pyplot as plt

for columna in aptos.select_dtypes(include='number').columns:

    plt.figure(figsize=(5,3))
    plt.hist(aptos[columna])
    plt.title(columna)
    plt.show()

# <FONT SIZE=5 COLOR="purple"> 2. El ciclo *while* </FONT>

El ciclo *while* es una estructura de control repetitiva que permite ejecutar un bloque de instrucciones mientras una condición determinada sea verdadera.

A diferencia del ciclo for, que suele utilizarse cuando se conoce de antemano el número de iteraciones, el while resulta especialmente útil cuando no se sabe cuántas veces debe repetirse una acción y esta depende del cumplimiento de una condición.

En cada iteración, el programa evalúa la condición y, si continúa siendo verdadera, ejecuta nuevamente el bloque de código.

Por esta razón, es importante que la condición cambie en algún momento dentro del ciclo para evitar repeticiones infinitas. El uso adecuado de while permite automatizar tareas, controlar procesos iterativos y gestionar situaciones donde la repetición depende de eventos o resultados que se producen durante la ejecución del programa.

```python
while condición:
    instrucciones
```

In [63]:
# Ejemplo 1
contador = 1

while contador <= 3:
    print(contador)
    contador += 1
else:
    print("El ciclo ha terminado")

1
2
3
El ciclo ha terminado

In [65]:
# ejemplo 2
while i < len(aptos):

    if aptos.loc[i, "precio"] > 600:
        print("Valor atípico encontrado:")
        print(aptos.loc[i])
        break

    i += 1

Valor atípico encontrado:
Unnamed: 0                             281
precio                               620.0
mt2                                  324.0
ubicacion                          poblado
estrato                                  6
alcobas                                  4
banos                                    4
balcon                                  no
parqueadero                             si
administracion                        0.55
avaluo                             338.427
terminado                               si
Tamano            el apartamento es grande
clasificacion       El apartamento es caro
Name: 280, dtype: object

In [66]:
def explorar_variable(datos, variable):

    print("Variable:", variable)
    print("Nulos:", datos[variable].isna().sum())

    if pd.api.types.is_numeric_dtype(datos[variable]):

        print("Tipo: Numérica")
        print(datos[variable].describe())

    else:

        print("Tipo: Categórica")
        print(datos[variable].value_counts())

In [71]:
explorar_variable(aptos, "terminado")

Variable: terminado
Nulos: 0
Tipo: Categórica
terminado
si    592
no    102
Name: count, dtype: int64