<table>
        <td>
        <td><img src="https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/logo_ECI.png" width="400"/></td>
        <td>&nbsp;</td>
        <td>
            <h1 style="font-size:200%;color:blue;text-align:center">    <FONT COLOR="blue"> DataFrames </p> Parte 2: Manipulación  </FONT>         </h1></td>         
        <td>
            <tp><p style="font-size:99%;text-align:center">Diplomado Ciencia de Datos </p></tp>
            <tp><p style="font-size:115%;text-align:center">2026-2</p></tp>
            <tp><p style="font-size:115%;text-align:center">Prof. Fabián Sánchez</p></tp>
        </td>
    </tr>
</table>

# <FONT SIZE=5 COLOR="red"> Contenidos del Notebook </FONT>

En este notebook encontrará:

- Manipulación de DataFrames

  + Ordenar por una variable
  + Renombrar una variable
  + Eliminar variables
  + Agregar una variable
  + Agrupaciones

- Filtros en el DataFrame

# <FONT SIZE=5 COLOR="green"> 1. Manipulación de DataFrame </FONT>

En esta sección revisaremos algunas operaciones y acciones que son importantes de conocer en un Data.Frame:

- Ordenar por una variable

- Renombrar una variable

- Eliminar una variable

- Agregar una variable

- Agrupar por categorias de una variable y aplicar funciones.

Para repasar

https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

In [ ]:
# librerías de trabajo
import pandas as pd
import numpy as np

In [ ]:
aptos = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/master/apartamentos.csv")
aptos.head()

In [ ]:
homicidios = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/homicidios.csv")
homicidios.head()

## <FONT SIZE=4 COLOR="magenta"> 1.1 Ordenar según una variable </FONT>

Para ordenar por una variable usamos la instrucción

$$datos.sort\_values(variable, ascending = False) $$

se usa:

- *ascending=True* :  ordena de menor a mayor. (default)
- *ascending=False* : ordena de mayor a menor.

In [ ]:
aptos.sort_values("mt2")

In [ ]:
aptos.sort_values("mt2" , ascending=False)

In [ ]:
# ordenamos por la variable precio de mayor a menor
aptos.sort_values("precio" , ascending =  False)

In [ ]:
# ordenamos por la variable precio de menor a mayor
aptos.sort_values("precio" , ascending =  True)

In [ ]:
# default ordena de menor a mayor por la variable ubicación
# lo hace por orden alfabético
aptos.sort_values("ubicacion", ascending = False)

In [ ]:
aptos.columns

## <FONT SIZE=4 COLOR="magenta"> 1.2 Renombrar una variable </FONT>

Podemos renombrar una columna de la siguiente forma usando la instrucción ***rename***

$$ datos.rename(columns=\{key : value, key : value\}, inplace=True) $$

 - Para cambiar el nombre de una variable debemos usar un diccionario donde las claves son las variables actuales y los valores son los nombres nuevos de las variables.
 - Recordemos que la instrucción **inplace** se usa para determinar si cambiamos el DataFrame original.

In [ ]:
# es recomendable hacer una copia
aptos2 = aptos.copy()

In [ ]:
aptos2

In [ ]:
aptos2.rename(columns={"administracion" : "admon"}, inplace = True)

In [ ]:
aptos2

In [ ]:
# renombrar avaluo como av de los datos aptos2
aptos2.rename(columns={"avaluo" : "av"}, inplace = True)

In [ ]:
aptos2.rename(columns={"avaluo" : "av"} , inplace= True)

In [ ]:
aptos2.head()

In [ ]:
# ejemplo
homicidios.columns

In [ ]:
# cambiar Estado civil por e.civil y Móvil Victima por m.victima
homicidios2 = homicidios.copy()
homicidios2.rename(columns={"Estado civil" : "e.civil" , "Móvil Victima" : "m.victima"}, inplace = True)

In [ ]:
homicidios2.columns

In [ ]:
aptos2.head()

## <FONT SIZE=4 COLOR="magenta"> 1.3 Eliminar filas y columnas</FONT>

Para eliminar una columna o una fila usamos la instrucción .drop

$$datos.drop(``nombre", axis = 1, inplace = T \, or \, F)$$

- *axis = 1* : es por columna
- *axis = 0* : es por  fila
- *inplace = T* : sobreescribe en el *df* original.
- *inplace = F* : no sobreescribe. Mantiene el original

In [ ]:
aptos2.columns

In [ ]:
aptos2.drop("Unnamed: 0" ,axis = 1 , inplace = True)

In [ ]:
aptos2.head()

In [ ]:
aptos2.drop(["precio", "mt2"], axis =1)

In [ ]:
aptos2.drop([4,6], axis = 0) # no sobreescribe

In [ ]:
aptos2.head(6)

## <FONT SIZE=4 COLOR="magenta"> 1.4 Agregar una variable </FONT>

Para agregar una variable usamos la instrucción

$$datos[``\text{nueva variable}"] = lista $$

In [ ]:
aptos2.head()

In [ ]:
# agregar la variable "precio/mt2"
aptos2["relacion pre/m2"] = aptos2.precio/aptos2.mt2

In [ ]:
aptos2.head()

In [ ]:
aptos2["ensayo"] = aptos.ubicacion + aptos.parqueadero

In [ ]:
aptos2

In [ ]:
aptos.precio.describe()

In [ ]:
import pandas as pd
import numpy  as np

In [ ]:
aptos = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/master/apartamentos.csv")
aptos.head()

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,1,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,2,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,3,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,4,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,5,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [ ]:
# aptos2 = aptos.copy()

In [ ]:
aptos.drop("Unnamed: 0", axis = 1, inplace = True )

In [ ]:
aptos.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

## <FONT SIZE=4 COLOR="magenta"> 1.5 Agrupaciones: ***groupby()*** </FONT>

Podemos hacer operaciones con las agrupaciones, así:

$$datos.groupby(``Variable")[``\text{segunda variable}"].funcion()$$

Por ejemplo, supongamos que queremos agrupar por escolaridad y calcular el promedio de las edades de cada uno de los grupos.

<center><img src="https://github.com/Fabian830348/cursos/blob/master/intro/groupby.png?raw=true" alt="centered image" width="450" height="350"></center> <center><figcaption> <FONT SIZE=1 COLOR="black"> Fuente: Elaboración propia  </FONT> <figcaption></center>

In [ ]:
aptos.precio.describe() # todos los apartamentos

count     694.000000
mean      317.762739
std       247.614914
min        25.000000
25%       160.000000
50%       245.000000
75%       380.000000
max      1700.000000
Name: precio, dtype: float64

In [ ]:
aptos.groupby("ubicacion")["precio"].mean()

ubicacion
aburra sur        193.672781
belen guayabal    168.865672
centro            130.815789
laureles          318.520548
norte             131.000000
occidente         164.304348
poblado           506.017317
Name: precio, dtype: float64

In [ ]:
aptos.groupby("parqueadero")["mt2"].describe()

             count        mean        std   min   25%    50%     75%    max
parqueadero
no           126.0   78.842222  36.949007  26.0  54.0   68.0   99.75  255.0
si           568.0  130.283257  77.698346  30.0  77.0  104.0  158.00  500.0

In [ ]:
aptos.groupby("ubicacion")["precio"].max()

ubicacion
aburra sur         330.0
belen guayabal     265.0
centro             260.0
laureles          1350.0
norte              175.0
occidente          320.0
poblado           1700.0
Name: precio, dtype: float64

In [ ]:
aptos.info()

In [ ]:
aptos.groupby(["ubicacion","balcon"])["precio"].mean()

ubicacion       balcon
aburra sur      no        139.894737
                si        209.272519
belen guayabal  no        160.416667
                si        170.709091
centro          no        115.277778
                si        144.800000
laureles        no        303.800000
                si        326.187500
norte           no        120.000000
                si        133.750000
occidente       no        155.785714
                si        170.121951
poblado         no        395.679694
                si        539.225728
Name: precio, dtype: float64

In [ ]:
aptos.ubicacion.value_counts()

ubicacion
poblado           268
aburra sur        169
laureles           73
occidente          69
belen guayabal     67
centro             38
norte              10
Name: count, dtype: int64

In [ ]:
# agrupar por ubicación
aptos.groupby("ubicacion")

In [ ]:
# calcula la media del precio en cada ubicación
aptos.groupby("ubicacion")["precio"].mean()

In [ ]:
# calcular las estadísticas del precio en cada ubicación
aptos.groupby("ubicacion")["precio"].describe()

In [ ]:
# si agrupamos por ubicacion, y parqueadero quiero saber el valor máximo del precio
aptos.groupby(["ubicacion" , "parqueadero"]).precio.max()

ubicacion       parqueadero
aburra sur      no              220.0
                si              330.0
belen guayabal  no              265.0
                si              260.0
centro          no              260.0
                si              210.0
laureles        no              190.0
                si             1350.0
norte           no              160.0
                si              175.0
occidente       no              320.0
                si              270.0
poblado         no              190.0
                si             1700.0
Name: precio, dtype: float64

In [ ]:
aptos.groupby(["ubicacion", "parqueadero"]).precio.min()

ubicacion       parqueadero
aburra sur      no              45.0
                si             112.0
belen guayabal  no              75.0
                si              86.0
centro          no              67.0
                si              70.0
laureles        no              25.0
                si             140.0
norte           no             100.0
                si              79.0
occidente       no              47.0
                si              53.0
poblado         no             170.0
                si             140.0
Name: precio, dtype: float64

# <FONT SIZE=5 COLOR="green"> 2. Filtros en un DataFrame </FONT>

En esta sección revisaremos algunos filtros en un dataframe. Para esto, generaremos algunas preguntas y buscaremos responderlas con los filtros.

De esta manera podemos seguir haciendo filtros y respondiendo algunas preguntas. Se debe tener en cuenta:

- Operadores de comparación :

    - **>** : mayor que
    - **<** : menor que
    - **>=**  : mayor o igual
    - **<=** : menor o igual
    - **!=** (diferente)

- Operadores lógicos:

    - **&**  : y
    - **|**  : o

<FONT SIZE=3 COLOR="blue"> Pregunta 1: ¿Cuántos apartamentos tienen precio mayor a 100 millones? </FONT>

In [ ]:
sum(aptos.precio > 100)

643

Rta: 643 apartamentos tienen precio mayor a 100 millones

In [ ]:
aptos[aptos.precio > 100]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si
5,140.0,71.00,norte,3,3,2,no,si,0.120,31.145508,si
6,145.0,54.83,norte,3,2,2,si,si,0.140,27.000000,si
7,160.0,69.00,norte,3,3,2,si,si,0.127,29.672435,si
...,...,...,...,...,...,...,...,...,...,...,...
689,498.0,180.00,laureles,5,4,3,si,si,0.570,233.784000,si
690,508.0,209.00,laureles,6,4,3,si,si,0.450,258.850000,si
691,550.0,149.00,laureles,6,3,4,no,si,0.747,326.157000,si
692,630.0,179.00,laureles,5,3,3,si,si,0.340,324.114000,si
693,1350.0,494.00,laureles,5,3,4,si,si,1.600,320.000000,si

In [ ]:
aptos.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [ ]:
10 > 5

True

In [ ]:
aptos.precio > 300

In [ ]:
sum(aptos.precio > 300)

253

In [ ]:
aptos[aptos.precio > 300]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
78,320.0,101.0,occidente,5,4,2,no,no,0.181,140.000,si
138,305.0,106.0,poblado,6,3,3,si,si,0.325,159.000,no
139,310.0,170.0,poblado,6,3,2,no,si,0.430,269.000,si
140,310.0,79.0,poblado,6,3,2,si,si,0.209,159.209,no
141,310.0,89.0,poblado,6,3,2,si,si,0.236,162.000,si
...,...,...,...,...,...,...,...,...,...,...,...
689,498.0,180.0,laureles,5,4,3,si,si,0.570,233.784,si
690,508.0,209.0,laureles,6,4,3,si,si,0.450,258.850,si
691,550.0,149.0,laureles,6,3,4,no,si,0.747,326.157,si
692,630.0,179.0,laureles,5,3,3,si,si,0.340,324.114,si
693,1350.0,494.0,laureles,5,3,4,si,si,1.600,320.000,si

In [ ]:
aptos.precio > 400

0      False
1      False
2      False
3      False
4      False
       ...
689     True
690     True
691     True
692     True
693     True
Name: precio, Length: 694, dtype: bool

In [ ]:
sum(aptos.precio > 400)

147

In [ ]:
# apartamentos de mas de 400 millones
aptos[aptos.precio > 400]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
210,410.0,220.00,poblado,6,3,3,si,si,0.795,400.805,si
211,410.0,168.50,poblado,6,3,3,no,si,0.536,277.500,no
212,410.0,132.98,poblado,6,4,3,si,si,0.800,369.977,si
213,420.0,197.00,poblado,6,3,3,si,si,0.545,263.615,si
214,420.0,163.00,poblado,6,3,3,si,si,0.360,227.471,si
...,...,...,...,...,...,...,...,...,...,...,...
689,498.0,180.00,laureles,5,4,3,si,si,0.570,233.784,si
690,508.0,209.00,laureles,6,4,3,si,si,0.450,258.850,si
691,550.0,149.00,laureles,6,3,4,no,si,0.747,326.157,si
692,630.0,179.00,laureles,5,3,3,si,si,0.340,324.114,si
693,1350.0,494.00,laureles,5,3,4,si,si,1.600,320.000,si

In [ ]:
# cuántos apartamentos de mas de 400 millones
len(aptos[aptos.precio > 400])

<FONT SIZE=3 COLOR="blue"> Pregunta 2: ¿Cuántos apartamentos del poblado tienen precio mayor a 200 millones? </FONT>

In [ ]:
sum((aptos.ubicacion == "poblado") & (aptos.precio > 200))

256

In [ ]:
aptos[(aptos.ubicacion == "poblado") & (aptos.precio > 200)  ]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
79,235.0,85.00,poblado,6,3,2,no,si,0.3185,121.997,si
92,205.0,77.14,poblado,6,2,2,no,si,0.3800,128.746,no
93,210.0,85.00,poblado,6,3,2,si,si,0.2500,128.746,si
94,210.0,75.00,poblado,6,2,2,no,si,0.2381,109.631,si
95,220.0,94.00,poblado,6,3,2,no,si,0.2500,107.858,si
...,...,...,...,...,...,...,...,...,...,...,...
342,1430.0,291.00,poblado,6,3,3,si,si,0.7490,701.731,si
343,1450.0,318.00,poblado,6,3,3,si,si,0.7490,611.027,si
344,1450.0,238.19,poblado,6,4,4,si,si,0.8286,675.072,si
345,1490.0,445.00,poblado,6,5,4,si,si,0.7490,701.731,si
346,1700.0,399.00,poblado,6,3,3,no,si,0.9340,701.731,si

<FONT SIZE=3 COLOR="blue"> Pregunta 3: ¿Cuántos apartamentos del sector laureles, tienen más (o igual) de 50 metros cuadrados y no cuentan con parqueadero? </FONT>

In [ ]:
sum((aptos.ubicacion == "laureles") & (aptos.mt2 >= 50) & (aptos.parqueadero == "no"))

3

In [ ]:
aptos[(aptos.ubicacion == "laureles") & (aptos.mt2 >= 50) & (aptos.parqueadero == "no")]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
621,135.0,66.0,laureles,5,2,1,si,no,0.0,55.076,no
626,190.0,112.0,laureles,5,4,2,si,no,0.0,55.388,no
644,25.0,118.0,laureles,5,3,2,si,no,0.0,95.885,si

<FONT SIZE=3 COLOR="blue"> Pregunta 4: ¿Cuántos apartamentos del sector laureles y el poblado? </FONT>

In [ ]:
# forma 1
sum((aptos.ubicacion == "poblado") | (aptos.ubicacion == "laureles"))

341

In [ ]:
# forma 2: con isin
sum(aptos["ubicacion"].isin(["laureles", "poblado"]))

341

<FONT SIZE=3 COLOR="blue"> Pregunta 5: Listar los apartamentos exceptos los ubicados en poblado</FONT>

In [ ]:
sum(aptos.ubicacion != "poblado")

426

In [ ]:
aptos[aptos.ubicacion != "poblado"]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si
...,...,...,...,...,...,...,...,...,...,...,...
689,498.0,180.00,laureles,5,4,3,si,si,0.570,233.784000,si
690,508.0,209.00,laureles,6,4,3,si,si,0.450,258.850000,si
691,550.0,149.00,laureles,6,3,4,no,si,0.747,326.157000,si
692,630.0,179.00,laureles,5,3,3,si,si,0.340,324.114000,si
693,1350.0,494.00,laureles,5,3,4,si,si,1.600,320.000000,si

In [ ]:
# apartamentos que el precio no sea mayor a 300
sum(aptos.precio <= 300)

441

In [ ]:
# apartamentos que el precio no sea mayor a 300
sum(~(aptos.precio > 300))

441

In [ ]:
# aptos : ubicacion que no están en laureles, con precio mayor a 250 mill y que tengan balcon
aptos[(aptos.ubicacion != "laureles") & (aptos.precio > 250) & (aptos.balcon == "si")]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
75,260.0,110.0,occidente,3,3,2,si,si,0.1700,74.000000,si
77,270.0,160.0,occidente,3,4,3,si,si,0.1300,160.000000,si
112,260.0,75.0,poblado,6,3,2,si,si,0.1900,230.000000,si
113,260.0,99.0,poblado,6,3,2,si,si,0.1900,160.093000,si
114,260.0,98.0,poblado,6,2,2,si,si,0.3230,158.000000,si
...,...,...,...,...,...,...,...,...,...,...,...
515,330.0,157.0,aburra sur,5,3,3,si,si,0.3776,212.810000,si
580,255.0,80.0,belen guayabal,5,2,2,si,si,0.0000,70.050464,si
581,260.0,137.0,belen guayabal,4,3,4,si,si,0.2970,150.000000,si
582,265.0,104.0,belen guayabal,4,3,2,si,no,0.0000,97.537000,si
620,260.0,226.0,centro,4,3,3,si,no,0.3260,158.914000,no

<FONT SIZE=3 COLOR="blue"> Pregunta 6: Cantidad de apartamento en un rango</FONT>

In [ ]:
#incluye los extremos
sum(aptos["precio"].between(100,200))

213