<table>
        <td>
        <td><img src="https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/logo_ECI.png" width="400"/></td>
        <td>&nbsp;</td>
        <td>
            <h1 style="font-size:200%;color:blue;text-align:center">    <FONT COLOR="blue"> DataFrames </p> Parte 3: .iloc y loc  </FONT>         </h1></td>         
        <td>
            <tp><p style="font-size:99%;text-align:center">Diplomado Ciencia de Datos </p></tp>
            <tp><p style="font-size:115%;text-align:center">2026-2</p></tp>
            <tp><p style="font-size:115%;text-align:center">Prof. Fabián Sánchez</p></tp>
        </td>
    </tr>
</table>

# <FONT SIZE=5 COLOR="red"> Contenidos del Notebook </FONT>

En este notebook encontrará:

- Selección de filas y columnas

  + *.iloc*
  + *.loc*

- Los métodos

  - *Replace*
  - *np.where*
  - *dropna()*
  - *isna()*
  - na_values() (instrucción de pandas)

Iniciaremos importando la librería *pandas*

In [ ]:
# importamos las librerías
import pandas as pd
import numpy as np

In [ ]:
# cargamos los datos: apartamentos
aptos = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/master/apartamentos.csv")
aptos.head()

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,1,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,2,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,3,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,4,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,5,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [ ]:
# cargamos los datos: hepatitis
hepatitis = pd.read_excel("https://raw.github.com/Fabian830348/Bases_Datos/master/hepatitis.xlsx")
hepatitis.head()

,Clase,Edad,Sexo,Esteroides,Antivirales,Fatiga,Malestar,Anorexia,Higado Grande,Cirrosis,Bazo palpable,Arañas,Ascites,Varices,Billirubina,Fosfato,SGOT,Albumina,Protina,Histologia
0,Vivo,30,Mujer,No,Sí,Sí,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,1.0,85,18,4.0,0,No
1,Vivo,50,Hombre,No,Sí,No,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,0.9,135,42,3.5,0,No
2,Vivo,78,Hombre,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,0.7,96,32,4.0,0,No
3,Vivo,31,Hombre,,No,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,0.7,46,52,4.0,80,No
4,Vivo,34,Hombre,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,1.0,0,200,4.0,0,No

Vamos a trabajar inicialmente con apartamentos

In [ ]:
# eliminamos la primera variable
aptos.drop(columns = ["Unnamed: 0"], inplace = True)

In [ ]:
aptos.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [ ]:
#seleccionar el elemento de la fila 3 y columna 5
aptos.iloc[1,2]

In [ ]:
# filas: 1 y 5 // columnas 5 y 9
aptos.iloc[[1,5] , [5,9]]

In [ ]:
# seleccionar la columna 2
aptos.iloc[:,2]

In [ ]:
aptos.iloc[ : , [3,4]]

In [ ]:
aptos.iloc[:, 2:].head()

In [ ]:
aptos.iloc[: , :2].head()

In [ ]:
# para las filas 4 en adelante
aptos.iloc[4:]

In [ ]:
aptos.iloc[3:10]

In [ ]:
aptos.head()

In [ ]:
aptos.loc[ : , "estrato" : ]

In [ ]:
aptos.head()

In [ ]:
y = aptos["precio"]
X = aptos.drop(columns = ["precio"])

In [ ]:
z = aptos.iloc[ : , 0]
w = aptos.loc[ : , ["mt2","alcobas","avaluo"]]

In [ ]:
w

# <FONT SIZE=5 COLOR="green"> 1. Acceder a los elementos del DataFrame </FONT>

Para acceder a los elementos, o a las filas o columnas del DataFrame podemos usar:

- ***iloc*** : para acceder por la posición
- ***loc.*** : para acceder por el nombre

Si usamos la primera instrucción

- ***df.iloc[i,j]*** : elemento de la fila i y columna j.

- ***df.iloc[i]*** : devuelve la fila i

- ***df.iloc[lista i , lista j]*** : devuelve un data.frame con las filas en lista i y columnas en columna j.

- ***df.iloc[:, j]*** : devuelve toda columna j.

Si usamos la instrucción **.loc**

- ***df.loc[nombre fila , nombre columna]***: es lo mismo anterior pero con los nombres.

- ***df[nombre columna]*** : devuelve las columnas en name columnas

- ***df.columna*** : otra forma para acceder a una columna que en el nombre no tenga espacios en blanco.


<br>
<center><img src="https://github.com/Fabian830348/cursos/blob/master/intro/DATAFRAME.png?raw=true" alt="centered image" width="600" height="350"></center> <center><figcaption> <FONT SIZE=1 COLOR="black"> Fuente: Elaboración propia  </FONT> <figcaption></center>

## <FONT SIZE=4 COLOR="magenta"> 1.1 Ejemplos con **.iloc** </FONT>

In [ ]:
aptos.head(5)

**Para seleccionar un elemento**

Elemento de la fila $i$ y columna $j$

$$datos.iloc[i,j]$$

In [ ]:
# para seleccionar un elemento de la fila 3 y fila 4
aptos.iloc[3,4]

In [ ]:
# la primera fila y columna 9
aptos.iloc[0, 9]

**Para seleccionar una fila**

Para seleccionar la fila $i$

$$datos.iloc[i]$$

In [ ]:
# para seleccionar una fila, simplemente no especificamos la columna
aptos.iloc[3]

In [ ]:
# si quiero varias filas
aptos.iloc[[0,3,4]]

In [ ]:
# si quiero un rango de filas. La instrucción range(a,b): inicia en a y termina en b-1
aptos.iloc[range(2,8)]

**Para seleccionar una columna**

Para seleccionar la columna $j$

$$datos.iloc[:,j]$$

In [ ]:
# para seleccionar una columna
aptos.iloc[:,2]

In [ ]:
# seleccionar varias columnas
aptos.iloc[:,[2,5,8]]

In [ ]:
# el uso de dos puntos 3: de tres en adelante
aptos.iloc[: , 3:]

In [ ]:
# el uso de dos puntos :3 de dos hacia atrás
aptos.iloc[: , :3]

**Varias columnas y varias filas**

In [ ]:
# filas 1 y 3 y columnas 0 y 1
aptos.iloc[[1,3], [0,1]]

In [ ]:
# las primeras 100 filas
aptos.iloc[0:100]

In [ ]:
# para seleccionar la segunda, tercera y primera fila
aptos.iloc[[1,2,0]]

## <FONT SIZE=4 COLOR="magenta"> 1.2 Ejemplos con **.loc** </FONT>

Veamos algunos ejemplos con **.loc**.

Recordemos que en *.iloc* se busca por posición y en *.loc* por nombre.

In [ ]:
aptos.columns

In [ ]:
aptos.head()

In [ ]:
# par seleccionar un elemento
aptos.loc[ 5 , "avaluo"]

In [ ]:
# la columna ubicacion
aptos.loc[:,"ubicacion"]

In [ ]:
# seleccionar la fila 5
aptos.loc[5]

In [ ]:
aptos.loc[: , "estrato": ]

In [ ]:
# seleccionar las columnas precio, mt2 y avaluo y las filas 2,5,6,7
aptos.loc[[2,5,6,7] , ["precio", "mt2", "avaluo"]]

In [ ]:
# otro ejemplo
aptos.loc[ [10,20,0,7] , ["ubicacion","parqueadero"]]

# <FONT SIZE=5 COLOR="green"> 2. La función Replace </FONT>

Podemos cambiar elementos de las columnas con la función `replace`

$$datos[``Variable"] = datos[``Variable"].replace(\{Valor\_actual : Valor\_nuevo\})$$

Veamos un ejemplo

In [ ]:
aptos.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [ ]:
# como vamos a modificar los datos es importante hacer una copia
aptos2 = aptos.copy()

In [ ]:
# cambiar varios valores de una columna
aptos2.ubicacion = aptos2.ubicacion.replace({"norte" : "FABIAN"})

In [ ]:
aptos2.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,FABIAN,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,FABIAN,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,FABIAN,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,FABIAN,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,FABIAN,4,3,2,si,no,0.000,39.567000,si

In [ ]:
# si queremos cambiar varios valores usamos un diccionario
aptos2.terminado = aptos2.terminado.replace({"no" : 0 , "si" : 1})

/tmp/ipykernel_1596/2552106275.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  aptos2.terminado = aptos2.terminado.replace({"no" : 0 , "si" : 1})

In [ ]:
aptos2.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,FABIAN,3,3,1,si,si,0.050,14.923002,0
1,93.0,56.92,FABIAN,2,2,1,si,si,0.069,27.000000,1
2,100.0,66.40,FABIAN,3,2,2,no,no,0.000,15.738427,0
3,123.0,61.85,FABIAN,2,3,2,si,si,0.130,27.000000,0
4,135.0,89.80,FABIAN,4,3,2,si,no,0.000,39.567000,1

In [ ]:
# cambiar una posición
aptos2.iloc[1,5] = "Fabian Sanchez"

/tmp/ipykernel_1596/259498542.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Fabian Sanchez' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  aptos2.iloc[1,5] = "Fabian Sanchez"

In [ ]:
# cambiar una posición
aptos2.iloc[2,1] = 15

In [ ]:
aptos2.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,FABIAN,3,3,1,si,si,0.050,14.923002,0
1,93.0,56.92,FABIAN,2,2,Fabian Sanchez,si,si,0.069,27.000000,1
2,100.0,15.00,FABIAN,3,2,2,no,no,0.000,15.738427,0
3,123.0,61.85,FABIAN,2,3,2,si,si,0.130,27.000000,0
4,135.0,89.80,FABIAN,4,3,2,si,no,0.000,39.567000,1

# <FONT SIZE=5 COLOR="green"> 3. Revisar donde hay cierto elemento </FONT>

Supongamos que queremos saber las posiciones donde el precio es de 120 millones.

Para saber una determinada posición usamos la instrucción

$$np.where(condicion)$$

In [ ]:
# para revisar las posiciones
np.where(aptos["precio"] == 120)

(array([ 27, 362, 363, 364, 365, 366, 528, 529]),)

In [ ]:
# para ver las filas
aptos.iloc[[ 27, 362, 363, 364, 365, 366, 528, 529]]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
27,120.0,57.0,occidente,3,2,2,no,no,0.000,68.302000,si
362,120.0,60.0,aburra sur,3,3,2,si,no,0.000,121.000000,si
363,120.0,58.0,aburra sur,3,3,2,no,si,0.125,52.633209,si
364,120.0,60.0,aburra sur,3,2,2,si,no,0.000,44.469049,si
365,120.0,80.0,aburra sur,3,2,1,si,no,0.000,31.083971,si
366,120.0,60.0,aburra sur,3,3,1,no,no,0.092,28.684288,si
528,120.0,58.0,belen guayabal,3,3,2,no,si,0.067,90.000000,si
529,120.0,117.0,belen guayabal,3,4,1,si,no,0.000,61.099000,no

In [ ]:
# también se puede con un filtro
aptos[aptos["precio"] == 120]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
27,120.0,57.0,occidente,3,2,2,no,no,0.000,68.302000,si
362,120.0,60.0,aburra sur,3,3,2,si,no,0.000,121.000000,si
363,120.0,58.0,aburra sur,3,3,2,no,si,0.125,52.633209,si
364,120.0,60.0,aburra sur,3,2,2,si,no,0.000,44.469049,si
365,120.0,80.0,aburra sur,3,2,1,si,no,0.000,31.083971,si
366,120.0,60.0,aburra sur,3,3,1,no,no,0.092,28.684288,si
528,120.0,58.0,belen guayabal,3,3,2,no,si,0.067,90.000000,si
529,120.0,117.0,belen guayabal,3,4,1,si,no,0.000,61.099000,no

In [ ]:
# cuántos apartamentos tienen precio de 120 millones
sum(aptos["precio"] == 120)

8

**Ejercicio**

**Parte 1**

- Exploración rápida de los datos

- Existen variables inconsistentes

- Hay datos faltantes

- Cambiar el nombre de la primera columna

- Eliminar la variable "reportes negativo"

- Arregle las inconsistencias

  - Si hay datos como "4o" podríamos salvarlos cambiando a 40
  
  - En este caso vamos a eliminar los datos faltantes

  - Unificar, si es necesario categorias

  - Eliminar datos que no son válidos en el contexto

**Parte 2**

- Analice las estadísticas de la variable **Edad**.

- Haga la tabla de frecuencia de la variable **Tarjeta** y de **Propietario de Vivienda**

- Ahora, haga la tabla cruzada de las variables anteriores.

- ¿Cuál es el promedio de **edad** por **propietario de vivienda**?

- Calcule las estadísticas descriptivas del **Gasto** dependiendo del número de dependientes.

**Parte 3**

- ¿Cuántas personas tienen 3 dependientes?

- ¿Cuántas personas son propietarios de vivienda y tienen más de 30 meses de historial?

- ¿Cuántas personas gastan menos de 200 us, no tienen vivienda propia y están entre 30 y 50 años?

- ¿Cuántas personas tienen más (o igual) de 6 cuentas activas y fue negada la tarjeta de crédito?

**Coerción**

La coerción es el proceso mediante el cual un lenguaje o una función convierte automáticamente un dato de un tipo a otro para poder realizar una operación.

In [ ]:
# ejemplo de coerción
pd.to_numeric(credito.Edad, errors='coerce')

In [ ]:
# identificamos donde hay errores
pd.to_numeric(credito.Edad, errors='coerce').isna()

In [ ]:
# identificamos las posiciones
np.where(pd.to_numeric(credito.Edad, errors='coerce').isna())

In [ ]:
# vamos a hacer coherción de datos: forzar a que se convierta en uno u otro tipo
credito.iloc[[ 11,  15, 116, 569]]

**veamos otra variable**

In [ ]:
credito.info()

In [ ]:
# revisar cadenas de texto en months
credito["months"].unique()

In [ ]:
pd.to_numeric(credito.months, errors='coerce').isna()

In [ ]:
sum(pd.to_numeric(credito.months, errors='coerce').isna())

In [ ]:
np.where(pd.to_numeric(credito.months, errors='coerce').isna())[0]

In [ ]:
credito.iloc[list(np.where(pd.to_numeric(credito.months, errors='coerce').isna())[0])]

**Para pensar un poco**

In [ ]:
# función para detectar
def problema_texto(datos, x):
  u = pd.to_numeric(datos[x], errors='coerce').isna()
  posiciones = np.where(u)[0]
  print(posiciones)
  return datos.iloc[posiciones]

In [ ]:
problema_texto(credito, "age")