<table>
        <td>
        <td><img src="https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/logo_ECI.png" width="400"/></td>
        <td>&nbsp;</td>
        <td>
            <h1 style="font-size:200%;color:blue;text-align:center">    <FONT COLOR="blue"> DataFrames </p> Parte 1: Generalidades  </FONT>         </h1></td>         
        <td>
            <tp><p style="font-size:99%;text-align:center">Diplomado Ciencia de Datos </p></tp>
            <tp><p style="font-size:115%;text-align:center">2026-2</p></tp>
            <tp><p style="font-size:115%;text-align:center">Prof. Fabián Sánchez</p></tp>
        </td>
    </tr>
</table>

# <FONT SIZE=5 COLOR="red"> Contenidos del Notebook </FONT>

En este notebook encontrará:

- Concepto de DataFrames
- Construir un DataFrame con pandas
- Carga de Datos
  + Desde drive
  + Desde el Github
- Exploración de datos
  + *.head()*
  + *.tail()*
  + *.shape*
  + *.info()*
  + *.columns*
  + *.describe()*
- Tablas de Frecuencias
  + *.value_counts()*
  + *.crosstab()*
- Estadísticas básicas
  + *.mean()*
  + *.median()*
  + *.mode()*
  + *.quantile()*

- Identificar datos faltantes

# <FONT SIZE=5 COLOR="green"> 1. Definición de DataFrame en Python </FONT>

- En este notebook trabajaremos uno de los objetos más importante cuando manipulamos y procesamos datos, los DataFrames.

- Recordemos que existen dos grupos grandes de datos que se denominan:

  - **Datos estructurados**: son aquellos que se pueden representar en un arreglo bidimensional: *fila-columna*. Es decir, las clásicas hojas de cálculo de excel.
  - **Datos no estructurados**: son los que no podemos representar en forma estructurada *fila-columna*. Por ejemplo, archivos de vídeo, audio, texto, imágenes, etc.


 De acuerdo con lo anterior definimos:

 ***Dataframe***: son arreglos o estructuras bidimensionales compuestos por fila y por columnas, y cuyos datos pueden ser de diferentes tipos: números, cadenas de texto, booleanos, etc.

   - Un dataframe tiene una forma matricial donde se identifican filas y columnas. Soporta diferentes tipos de datos.
   - Un dataframe está compuesto por vectores (columnas) cada una de las cuales describe una atributo o característica (variable) de una población.
   - La librería más usada para manipulación de dataframes se denomina ***pandas*** en Python. Si trabajas en *RStudio* es ***dplyr***

<br>
<center><img src="https://github.com/Fabian830348/cursos/blob/master/intro/DATAFRAME.png?raw=true" alt="centered image" width="600" height="350"></center> <center><figcaption> <FONT SIZE=1 COLOR="black"> Fuente: Elaboración propia  </FONT> <figcaption></center>

Iniciaremos importando la librería *pandas* y *numpy*

In [ ]:
import pandas as pd
import numpy as np

# <FONT SIZE=5 COLOR="green"> 2. Generación de un DataFrame </FONT>

En esta sección revisaremos cómo se genera un dataframe a partir de:

- Listas
- Un diccionario

para generar un dataframe usamos la instrucción de pandas

$$pd.DataFrame()$$

## <FONT SIZE=4 COLOR="magenta"> 2.1 A partir de una Lista </FONT>

In [ ]:
lista1 = ["Fabian" , 30 , 164 , "Doctorado"]
lista2 = ["Camilo" , 24 , 174 , "Maestría"]
lista3 = ["Ana María" , 20 , 180 , "Profesional"]
lista4 = ["Andrea" , 36 , 154 , "Doctorado"]
lista5 = ["Mariana" , 45 , 164 , "Doctorado"]

pd.DataFrame([lista1, lista2, lista3, lista4, lista5])

           0   1    2            3
0     Fabian  30  164    Doctorado
1     Camilo  24  174     Maestría
2  Ana María  20  180  Profesional
3     Andrea  36  154    Doctorado
4    Mariana  45  164    Doctorado

observe que enumera las columnas pero no tiene nombres.

Ahora, vamos a colocar nombre a las columnas

In [ ]:
lista1 = ["Fabian" , 30 , 164 , "Doctorado"]
lista2 = ["Camilo" , 24 , 174 , "Maestría"]
lista3 = ["Ana María" , 20 , 180 , "Profesional"]
lista4 = ["Andrea" , 36 , 154 , "Doctorado"]
lista5 = ["Mariana" , 45 , 164 , "Doctorado"]

df1 = pd.DataFrame([lista1, lista2, lista3, lista4, lista5],                          # datos
              columns = ["Nombre", "Edad", "Estatura(cm)", "Nivel_Educativo"])        # variables

In [ ]:
df1

      Nombre  Edad  Estatura(cm) Nivel_Educativo
0     Fabian    30           164       Doctorado
1     Camilo    24           174        Maestría
2  Ana María    20           180     Profesional
3     Andrea    36           154       Doctorado
4    Mariana    45           164       Doctorado

## <FONT SIZE=4 COLOR="magenta"> 2.2 A partir de un diccionario </FONT>

Para construir el DataFrame a partir de un diccionario se usa

$$pd.DataFrame(diccionario)$$

Si se tienen las listas que representan las columnas, el dataframe se construye de la siguiente forma

In [ ]:
lista1 = [30,40,50,60]
lista2 = ["Audi", "BMW", "Renault", "ByD"]
lista3 = [1.76, 1.50, 1.60, 1.80]
lista4 = ["Carlos", "Juan", "Hugo", "Ana"]

diccionario = {"Edad" : lista1,
               "Marca_Auto" : lista2,
               "Estatura(mts)" : lista3,
               "Nombre" : lista4}

df2 =pd.DataFrame(diccionario)
df2

   Edad Marca_Auto  Estatura(mts)  Nombre
0    30       Audi           1.76  Carlos
1    40        BMW           1.50    Juan
2    50    Renault           1.60    Hugo
3    60        ByD           1.80     Ana

Podemos colocar el diccionario directamente dentro de la expresión DataFrame

In [ ]:
diccionario = {"Nombre" : ["Hugo", "Andres", "Camilo", "Ana" ],
               "Edad" : [70, 40, 24, 10],
               "Estatura" : [180, 170, 150, 176],
               "Nivel_Educativo" : ["Doctorado", "Profesional", "Maestría","Maestría"]}

df3 = pd.DataFrame(diccionario)
df3

   Nombre  Edad  Estatura Nivel_Educativo
0    Hugo    70       180       Doctorado
1  Andres    40       170     Profesional
2  Camilo    24       150        Maestría
3     Ana    10       176        Maestría

In [ ]:
# ejemplo
nombres = ["Hugo", "Andres", "Camilo", "Ana"]
edad =  [70, 40, 24, 10]
pd.DataFrame({"nombres" : nombres , "edad" : edad})

  nombres  edad
0    Hugo    70
1  Andres    40
2  Camilo    24
3     Ana    10

Es importante conocer como generar un DataFrame desde una lista o diccionario, sin embargo lo más importante es saber cómo cargar datos de diferentes fuentes.

# <FONT SIZE=5 COLOR="Green"> 3. Carga de Datos </FONT></center>

Vamos a cargar datos (dataframe) de dos formas diferentes:

  - Desde el pc
  - Desde ***GoogleDrive()***
  - Desde un repositorio externo. Generalmente GitHub.

## <FONT SIZE=4 COLOR="magenta"> 3.1 Cargar desde el PC </FONT></center>

- En la parte lateral izquiera aparece un ícono de carpeta: Dar click

- Aparece un título que dice archivo. Dar click en el primer ícono (flecha).

- Cargar el archivo a la sesión

In [ ]:
# Ejemplo 1: cargar el archivo homicidios desde archivos
homicidios =

In [ ]:
# Ejemplo 2: cargar el archivo: tabla personas
tabla_personas =

## <FONT SIZE=4 COLOR="magenta"> 3.1 Usando Google-Drive </FONT></center>

- Para conectarse al drive usamos la siguiente instrucción

In [ ]:
# instrucción para conectarse con drive
from google.colab import drive
drive.mount('/content/drive')

Siempre que trabajemos con dataframes es importante cargar la librería pandas.

Para cargar los archivos buscamos la ubicación de los mismos y la ruta en la parte izquierda del notebook

Vamos a importar los datos denominados *apartamentos.csv*

Como el archivo está en formato *.csv*, que es un archivo separado por coma usamos la función

$$pd.read\_csv(``link")$$

In [ ]:
# Ejemplo 3 cargar el conjunto de datos apartamentos.csv desde el drive
aptos =

Si el archivo está en formato *.json* :  javascrip object notation

$$pd.read\_json(``link")$$

In [ ]:
# Ejemplo 4 cargar el conjunto de datos espectro.json desde el drive
espectro =

Si el archivo está en formato *.xlsx*, usamos la función

$$pd.read\_excel(link)$$

In [ ]:
# Ejemplo 5 traer el conjunto de datos hepatitis
hepatitis =

## <FONT SIZE=4 COLOR="magenta"> 3.3 Usando Repositorio Externo url </FONT></center>

Para importar datos desde un repositorio externo, debemos conocer la *url*. Algunos ejemplos:

- https://github.com/stedy/Machine-Learning-with-R-datasets

- https://archive.ics.uci.edu/datasets?skip=10&take=10&sort=desc&orderBy=NumHits&search=

- https://www.datos.gov.co/browse?limitTo=datasets&provenance=official&sortBy=newest&pageSize=20&category=Salud+y+Protecci%C3%B3n+Social&page=1

In [ ]:
# conjunto de datos crédito .csv
credito =

In [ ]:
# conjunto de datos diabetes .csv  : https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/diabetes.csv
diabetes =

# <FONT SIZE=5 COLOR="green"> 4. Instrucciones básicas de exploración de DataFrames</FONT>

Algunas instrucciones básicas de un dataframe:

**df.info()** : Devuelve información (número de filas, número de columnas, índices, tipo de las columnas y memoria usado) sobre el DataFrame df.

**df.shape** : Devuelve una pareja con el número de filas y columnas del DataFrame df.

**df.size** : Devuelve el número de elementos del DataFrame.

**df.columns** : Devuelve una lista con los nombres de las columnas del DataFrame df.

**df.index** : Devuelve una lista con los nombres de las filas del DataFrame df.

**df.dtypes** : Devuelve una serie con los tipos de datos de las columnas del DataFrame df.

**df.head(n)** : Devuelve las n primeras filas del DataFrame df.

**df.tail(n)** : Devuelve las n últimas filas del DataFrame df.

**df.append({})** : para agregar una nueva fila al dataframe

A continuación revisaremos algunas de ellas con el conjunto de datos apartamentos

Para lo que sigue vamos a usar el conjunto **apartamentos**

In [ ]:
# conjunto de datos aptos
aptos

1. Usamos la instrucción **head()** para explorar la cabeza de los datos

- Podemos indicar cuántos datos queremos visualizar simplemente con $head(n)$, sonde $n$ indica el número de registros que queremos ver.

In [ ]:
# para visualizar los primeros datos.

2. Usamos la instrucción **tail()** para explorar los últimos datos

In [ ]:
# para visualizar los últimos datos. (n=6)

3. Con la instrucción **shape** miramos el tamaño de nuestros datos

In [ ]:
# tamaño de los datos

el conjunto tiene 694 filas y 12 columnas.

4. Para explorar nombre de las variables o columnas **columns**

In [ ]:
# revisar las columnas de aptos

5. **info()** es un resumen de las variables y su clasificación. Además, podemos identificar datos faltantes (NA) en cada una de ellas.

In [ ]:
# información de los aptos

Es importante verificar que las variables del conjunto de datos hayan sido cargadas en el tipo adecuado.

6. Para revisar las estadísticas generales de las variables cuantitativas usamos **describe()**

In [ ]:
# estadísticas descriptivas numéricas.

In [ ]:
# si queremos las estadísticas (frecuencias) de las variables cualitativas

In [ ]:
# datos unicos de la variable ubicación

In [ ]:
# tabla de frecuencia de ubicacion

7. Para acceder a una o varias variable del data.frame podemos usar la instrucción

- **datos["nombre de la variable"]**

veamos algunos ejemplos

In [ ]:
# podemos acceder a una o más variables del data.frame data[]
aptos["precio"]

In [ ]:
# acceder a varias columnas
aptos[["ubicacion","estrato","banos"]]

In [ ]:
# valores únicos de una variable
aptos.ubicacion.unique()

In [ ]:
# podemos revisar unas estadísticas básicas de una variable numérica con .describe()
aptos["precio"].describe()

In [ ]:
aptos[["precio", "mt2"]]

También se puede acceder al nombre de una variable asi:
$$datos.variable$$
Siempre y cuando el nombre de la variable no tenga espacios o caracteres especiales.

In [ ]:
aptos.precio

# <FONT SIZE=5 COLOR="green"> 5. Tabla de frecuencias </FONT>

Para hacer el conteo de las categorías o clases de una variables podemos usar la instrucción ***.value_counts***

- **datos["variable"].value_counts()**

Ejemplo: Para hacer una tabla de frecuencias de la variable *ubicacion*

In [ ]:
# tabla de frecuencias de la variable ubicacion
aptos.ubicacion.value_counts()

ubicacion
poblado           268
aburra sur        169
laureles           73
occidente          69
belen guayabal     67
centro             38
norte              10
Name: count, dtype: int64

In [ ]:
aptos["ubicacion"].value_counts()

ubicacion
poblado           268
aburra sur        169
laureles           73
occidente          69
belen guayabal     67
centro             38
norte              10
Name: count, dtype: int64

In [ ]:
# cuantos aptos no tienen parqueadero
aptos.parqueadero.value_counts()

parqueadero
si    568
no    126
Name: count, dtype: int64

In [ ]:
# conteo de la variable terminado-aptos
aptos["terminado"].value_counts()

terminado
si    592
no    102
Name: count, dtype: int64

In [ ]:
aptos.precio.value_counts()

precio
220.0    20
210.0    19
260.0    18
190.0    16
140.0    14
         ..
102.0     1
147.0     1
25.0      1
343.0     1
508.0     1
Name: count, Length: 189, dtype: int64

In [ ]:
aptos.estrato.value_counts()

estrato
6    242
3    161
5    145
4    138
2      8
Name: count, dtype: int64

Si queremos una tabla cruzada entre dos variables categóricas usamos la instrucción:

$$pd.crosstab(variable1, variable2)$$

In [ ]:
pd.crosstab( aptos.estrato, aptos.ubicacion)

ubicacion,aburra sur,belen guayabal,centro,laureles,norte,occidente,poblado
estrato,,,,,,,
2,3,1,0,0,2,2,0
3,73,30,16,0,5,37,0
4,57,21,21,14,3,15,7
5,35,15,1,56,0,15,23
6,1,0,0,3,0,0,238

In [ ]:
# tabla cruzada de ubicación y estrato
pd.crosstab(aptos.ubicacion , aptos.estrato)

estrato         2   3   4   5    6
ubicacion
aburra sur      3  73  57  35    1
belen guayabal  1  30  21  15    0
centro          0  16  21   1    0
laureles        0   0  14  56    3
norte           2   5   3   0    0
occidente       2  37  15  15    0
poblado         0   0   7  23  238

In [ ]:
# puedo cruzar tres variables??
pd.crosstab(aptos.ubicacion, [aptos.balcon , aptos.terminado])

balcon          no      si
terminado       no  si  no   si
ubicacion
aburra sur       9  29   9  122
belen guayabal   1  11   7   48
centro           9   9   5   15
laureles         3  22   2   46
norte            1   1   2    6
occidente        3  25  10   31
poblado         11  51  30  176

In [ ]:
# tabla de frecuencia (contingencia) ubicacion y parqueadero
# las dos instrucciones adicionales sirven para totalizar
pd.crosstab(aptos["ubicacion"],                 # variable 1
            aptos["parqueadero"],               # variable 2
            margins= True,                      # muestra el total
            margins_name= "SubTotal")           # nombre del total

parqueadero      no   si  SubTotal
ubicacion
aburra sur       39  130       169
belen guayabal   31   36        67
centro           28   10        38
laureles          3   70        73
norte             3    7        10
occidente        20   49        69
poblado           2  266       268
SubTotal        126  568       694

In [ ]:
# tabla de contingencia de tres variables cruzadas
pd.crosstab(aptos["ubicacion"], [aptos["balcon"], aptos["estrato"]])

balcon         no                 si
estrato         2   3   4   5   6  2   3   4   5    6
ubicacion
aburra sur      2  26   6   4   0  1  47  51  31    1
belen guayabal  0   6   5   1   0  1  24  16  14    0
centro          0   8  10   0   0  0   8  11   1    0
laureles        0   0   5  18   2  0   0   9  38    1
norte           0   2   0   0   0  2   3   3   0    0
occidente       1  17   7   3   0  1  20   8  12    0
poblado         0   0   2   9  51  0   0   5  14  187

**Ejercicio**

- Tabla de frecuencia de Estado Civil

- Tabla de frecuencia cruza de Sexo y Estado Civil del conjunto de datos homicidios

# <FONT SIZE=5 COLOR="green"> 6. Algunas funciones importantes </FONT>

A continuación revisaremos algunas estadísticas básicas

- Media
- Mediana
- Moda
- Cuantiles

1. Media o promedio: **.mean()**

- Es el "equilibrio" de los datos.
- Se usa para variables cuantitativas.
- Siempre está entre el mínimo y máximo de los datos.
- Es sensible a datos atípicos. Por está razón se debe tener cuidado con su interpretación.

In [ ]:
aptos.precio.mean()

np.float64(317.7627391930836)

In [ ]:
aptos.precio.describe()

count     694.000000
mean      317.762739
std       247.614914
min        25.000000
25%       160.000000
50%       245.000000
75%       380.000000
max      1700.000000
Name: precio, dtype: float64

2. Mediana: **.median()**

- Es el valor que divide los datos en dos partes iguales (50%-50%)
- Aplica para variables cuantitativas
- Puede o no estar en el conjunto de datos. Depende si se tiene un número par o impar de elementos.
- No se ve afectada por la existencia de datos atípicos. Por está razón en ocaciones se usa para imputación.

In [ ]:
aptos.precio.median()

245.0

3. Moda: **.mode()**

- Es el valor que más se repite. Es decir el que tiene mayor frecuencia
- Aplica para variables cualitativas y cuantitativas
- UN conjunto puede no tener o tener múltiples modas.

In [ ]:
aptos.precio.mode()

0    220.0
Name: precio, dtype: float64

In [ ]:
aptos.ubicacion.mode()

0    poblado
Name: ubicacion, dtype: object

In [ ]:
aptos.ubicacion.describe()

count         694
unique          7
top       poblado
freq          268
Name: ubicacion, dtype: object

4. Máximo y mínimo del conjunto: **.max** y **.min**

In [ ]:
aptos.precio.max()

1700.0

In [ ]:
aptos.precio.min()

25.0

5. Cuartiles: $Q_1$, $Q_2$ y $Q_3$

- Se calculan para variables cuantitativas
- $Q_1$: el valor que acumula el 25% de los datos
- $Q_2$: es el valor que acumula el 50% de los datos. En ese orden de ideas es la mediana.
- $Q_3$ es el valor que acumula el 75% de los datos.
- Para calcula en Python estos valores y en general los cuantiles usamos la librería *numpy* y la instrucción:

$$ perc\_{n} = np.percentile(variable, n) $$

Veamos algunos ejemplos con la variable *precio* de *aptos*.

In [ ]:
import numpy as np
print(np.percentile(aptos.precio,25))
print(np.percentile(aptos.precio,50))
print(np.percentile(aptos.precio,75))
print(np.percentile(aptos.precio,80))

160.0
245.0
380.0
421.9999999999999

# <FONT SIZE=5 COLOR="green"> 7. Identificar datos faltantes </FONT>

En esta sección revisaremos como identificar la cantidad de datos faltantes.

In [ ]:
# identificar datos faltantes  : isna
aptos.isna.sum()

In [ ]:
# identificar datos faltantes  : isnull()
aptos.isnull().sum()

Unnamed: 0        0
precio            0
mt2               0
ubicacion         0
estrato           0
alcobas           0
banos             0
balcon            0
parqueadero       0
administracion    0
avaluo            0
terminado         0
dtype: int64

In [ ]:
aptos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      694 non-null    int64
 1   precio          694 non-null    float64
 2   mt2             694 non-null    float64
 3   ubicacion       694 non-null    object
 4   estrato         694 non-null    int64
 5   alcobas         694 non-null    int64
 6   banos           694 non-null    int64
 7   balcon          694 non-null    object
 8   parqueadero     694 non-null    object
 9   administracion  694 non-null    float64
 10  avaluo          694 non-null    float64
 11  terminado       694 non-null    object
dtypes: float64(4), int64(4), object(4)
memory usage: 65.2+ KB

In [ ]:
# calcular datos faltantes de tabla_personas

Fecha                 0
Departamento          0
Municipio             0
Día                   0
Hora                  0
Barrio                0
Zona                  0
Clase de sitio        0
Arma empleada         0
Móvil Agresor         0
Móvil Victima         0
Edad                  0
Sexo                  0
Estado civil          0
País de nacimiento    0
Clase de empleado     0
Profesión             0
Escolaridad           0
Código DANE           0
Cantidad              0
dtype: int64