<table>
        <td>
        <td><img src="https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/logo_ECI.png" width="400"/></td>
        <td>&nbsp;</td>
        <td>
            <h1 style="font-size:200%;color:blue;text-align:center">    <FONT COLOR="blue"> DataFrames </p> Parte 3: .iloc y loc  </FONT>         </h1></td>         
        <td>
            <tp><p style="font-size:99%;text-align:center">Diplomado Ciencia de Datos </p></tp>
            <tp><p style="font-size:115%;text-align:center">2026-2</p></tp>
            <tp><p style="font-size:115%;text-align:center">Prof. Fabián Sánchez</p></tp>
        </td>
    </tr>
</table>

# <FONT SIZE=5 COLOR="red"> Contenidos del Notebook </FONT>

En este notebook encontrará:

- Selección de filas y columnas

  + *.iloc*
  + *.loc*

- Los métodos

  - *Replace*
  - *np.where*
  - *dropna()*
  - *isna()*
  - na_values() (instrucción de pandas)

Iniciaremos importando la librería *pandas*

In [1]:
# importamos las librerías
import pandas as pd
import numpy as np

In [3]:
# cargamos los datos: apartamentos
aptos = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/master/apartamentos.csv")
aptos.head()

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,1,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,2,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,3,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,4,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,5,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [4]:
# cargamos los datos: hepatitis
hepatitis = pd.read_excel("https://raw.github.com/Fabian830348/Bases_Datos/master/hepatitis.xlsx")
hepatitis.head()

,Clase,Edad,Sexo,Esteroides,Antivirales,Fatiga,Malestar,Anorexia,Higado Grande,Cirrosis,Bazo palpable,Arañas,Ascites,Varices,Billirubina,Fosfato,SGOT,Albumina,Protina,Histologia
0,Vivo,30,Mujer,No,Sí,Sí,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,1.0,85,18,4.0,0,No
1,Vivo,50,Hombre,No,Sí,No,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,0.9,135,42,3.5,0,No
2,Vivo,78,Hombre,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,0.7,96,32,4.0,0,No
3,Vivo,31,Hombre,,No,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,0.7,46,52,4.0,80,No
4,Vivo,34,Hombre,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,1.0,0,200,4.0,0,No

Vamos a trabajar inicialmente con apartamentos

In [5]:
# eliminamos la primera variable
aptos.drop(columns = ["Unnamed: 0"], inplace = True)

In [6]:
aptos.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

# <FONT SIZE=5 COLOR="green"> 1. Acceder a los elementos del DataFrame </FONT>

Para acceder a los elementos, o a las filas o columnas del DataFrame podemos usar:

- ***iloc*** : para acceder por la posición
- ***loc.*** : para acceder por el nombre

Si usamos la primera instrucción

- ***df.iloc[i,j]*** : elemento de la fila i y columna j.

- ***df.iloc[i]*** : devuelve la fila i

- ***df.iloc[lista i , lista j]*** : devuelve un data.frame con las filas en lista i y columnas en columna j.

- ***df.iloc[:, j]*** : devuelve toda columna j.

Si usamos la instrucción **.loc**

- ***df.loc[nombre fila , nombre columna]***: es lo mismo anterior pero con los nombres.

- ***df[nombre columna]*** : devuelve las columnas en name columnas

- ***df.columna*** : otra forma para acceder a una columna que en el nombre no tenga espacios en blanco.


<br>
<center><img src="https://github.com/Fabian830348/cursos/blob/master/intro/DATAFRAME.png?raw=true" alt="centered image" width="600" height="350"></center> <center><figcaption> <FONT SIZE=1 COLOR="black"> Fuente: Elaboración propia  </FONT> <figcaption></center>

## <FONT SIZE=4 COLOR="magenta"> 1.1 Ejemplos con **.iloc** </FONT>

In [7]:
aptos.head(5)

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

**Para seleccionar un elemento**

Elemento de la fila $i$ y columna $j$

$$datos.iloc[i,j]$$

In [11]:
# para seleccionar un elemento de la fila 3 y fila 4
aptos.iloc[3,4]

np.int64(3)

In [12]:
# la primera fila y columna 9
aptos.iloc[0, 9]

np.float64(14.923002)

**Para seleccionar una fila**

Para seleccionar la fila $i$

$$datos.iloc[i]$$

In [13]:
# para seleccionar una fila, simplemente no especificamos la columna
aptos.iloc[3]

precio            123.0
mt2               61.85
ubicacion         norte
estrato               2
alcobas               3
banos                 2
balcon               si
parqueadero          si
administracion     0.13
avaluo             27.0
terminado            no
Name: 3, dtype: object

In [14]:
# si quiero varias filas
aptos.iloc[[0,3,4]]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.05,14.923002,no
3,123.0,61.85,norte,2,3,2,si,si,0.13,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.00,39.567000,si

In [15]:
# si quiero un rango de filas. La instrucción range(a,b): inicia en a y termina en b-1
aptos.iloc[range(2,8)]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si
5,140.0,71.00,norte,3,3,2,no,si,0.120,31.145508,si
6,145.0,54.83,norte,3,2,2,si,si,0.140,27.000000,si
7,160.0,69.00,norte,3,3,2,si,si,0.127,29.672435,si

**Para seleccionar una columna**

Para seleccionar la columna $j$

$$datos.iloc[:,j]$$

In [16]:
# para seleccionar una columna
aptos.iloc[:,2]

0         norte
1         norte
2         norte
3         norte
4         norte
         ...
689    laureles
690    laureles
691    laureles
692    laureles
693    laureles
Name: ubicacion, Length: 694, dtype: object

In [ ]:
# seleccionar varias columnas
aptos.iloc[:,[2,5,8]]

In [17]:
# el uso de dos puntos 3: de tres en adelante
aptos.iloc[: , 3:]

,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,3,3,1,si,si,0.050,14.923002,no
1,2,2,1,si,si,0.069,27.000000,si
2,3,2,2,no,no,0.000,15.738427,no
3,2,3,2,si,si,0.130,27.000000,no
4,4,3,2,si,no,0.000,39.567000,si
...,...,...,...,...,...,...,...,...
689,5,4,3,si,si,0.570,233.784000,si
690,6,4,3,si,si,0.450,258.850000,si
691,6,3,4,no,si,0.747,326.157000,si
692,5,3,3,si,si,0.340,324.114000,si
693,5,3,4,si,si,1.600,320.000000,si

In [18]:
# el uso de dos puntos :3 de dos hacia atrás
aptos.iloc[: , :3]

     precio     mt2 ubicacion
0      79.0   43.16     norte
1      93.0   56.92     norte
2     100.0   66.40     norte
3     123.0   61.85     norte
4     135.0   89.80     norte
..      ...     ...       ...
689   498.0  180.00  laureles
690   508.0  209.00  laureles
691   550.0  149.00  laureles
692   630.0  179.00  laureles
693  1350.0  494.00  laureles

[694 rows x 3 columns]

**Varias columnas y varias filas**

In [ ]:
# filas 1 y 3 y columnas 0 y 1
aptos.iloc[[1,3], [0,1]]

In [ ]:
# las primeras 100 filas
aptos.iloc[0:100]

In [ ]:
# para seleccionar la segunda, tercera y primera fila
aptos.iloc[[1,2,0]]

## <FONT SIZE=4 COLOR="magenta"> 1.2 Ejemplos con **.loc** </FONT>

Veamos algunos ejemplos con **.loc**.

Recordemos que en *.iloc* se busca por posición y en *.loc* por nombre.

In [ ]:
aptos.columns

Index(['precio', 'mt2', 'ubicacion', 'estrato', 'alcobas', 'banos', 'balcon',
       'parqueadero', 'administracion', 'avaluo', 'terminado'],
      dtype='object')

In [ ]:
aptos.head()

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,1,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,2,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,3,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,4,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,5,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [ ]:
# par seleccionar un elemento
aptos.loc[ 5 , "avaluo"]

np.float64(31.145508)

In [ ]:
# la columna ubicacion
aptos.loc[:,"ubicacion"]

0         norte
1         norte
2         norte
3         norte
4         norte
         ...
689    laureles
690    laureles
691    laureles
692    laureles
693    laureles
Name: ubicacion, Length: 694, dtype: object

In [19]:
# seleccionar la fila 5
aptos.loc[5]

precio                140.0
mt2                    71.0
ubicacion             norte
estrato                   3
alcobas                   3
banos                     2
balcon                   no
parqueadero              si
administracion         0.12
avaluo            31.145508
terminado                si
Name: 5, dtype: object

In [20]:
aptos.loc[: , "estrato": ]

,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,3,3,1,si,si,0.050,14.923002,no
1,2,2,1,si,si,0.069,27.000000,si
2,3,2,2,no,no,0.000,15.738427,no
3,2,3,2,si,si,0.130,27.000000,no
4,4,3,2,si,no,0.000,39.567000,si
...,...,...,...,...,...,...,...,...
689,5,4,3,si,si,0.570,233.784000,si
690,6,4,3,si,si,0.450,258.850000,si
691,6,3,4,no,si,0.747,326.157000,si
692,5,3,3,si,si,0.340,324.114000,si
693,5,3,4,si,si,1.600,320.000000,si

In [21]:
# seleccionar las columnas precio, mt2 y avaluo y las filas 2,5,6,7
aptos.loc[[2,5,6,7] , ["precio", "mt2", "avaluo"]]

   precio    mt2     avaluo
2   100.0  66.40  15.738427
5   140.0  71.00  31.145508
6   145.0  54.83  27.000000
7   160.0  69.00  29.672435

In [22]:
# otro ejemplo
aptos.loc[ [10,20,0,7] , ["ubicacion","parqueadero"]]

    ubicacion parqueadero
10  occidente          no
20  occidente          si
0       norte          si
7       norte          si

# <FONT SIZE=5 COLOR="green"> 2. La función Replace </FONT>

Podemos cambiar elementos de las columnas con la función `replace`

$$datos[``Variable"] = datos[``Variable"].replace(\{Valor\_actual : Valor\_nuevo\})$$

Veamos un ejemplo

In [ ]:
aptos.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [23]:
# como vamos a modificar los datos es importante hacer una copia
aptos2 = aptos.copy()

In [24]:
# cambiar varios valores de una columna
aptos2.ubicacion = aptos2.ubicacion.replace({"norte" : "FABIAN"})

In [25]:
aptos2.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,FABIAN,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,FABIAN,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,FABIAN,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,FABIAN,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,FABIAN,4,3,2,si,no,0.000,39.567000,si

In [26]:
# si queremos cambiar varios valores usamos un diccionario
aptos2.terminado = aptos2.terminado.replace({"no" : 0 , "si" : 1})

/tmp/ipykernel_3631/2552106275.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  aptos2.terminado = aptos2.terminado.replace({"no" : 0 , "si" : 1})

In [27]:
aptos2.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,FABIAN,3,3,1,si,si,0.050,14.923002,0
1,93.0,56.92,FABIAN,2,2,1,si,si,0.069,27.000000,1
2,100.0,66.40,FABIAN,3,2,2,no,no,0.000,15.738427,0
3,123.0,61.85,FABIAN,2,3,2,si,si,0.130,27.000000,0
4,135.0,89.80,FABIAN,4,3,2,si,no,0.000,39.567000,1

In [28]:
# cambiar una posición
aptos2.iloc[1,5] = "Fabian Sanchez"

/tmp/ipykernel_3631/259498542.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Fabian Sanchez' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  aptos2.iloc[1,5] = "Fabian Sanchez"

In [29]:
# cambiar una posición
aptos2.iloc[2,1] = 15

In [32]:
aptos2.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,FABIAN,3,3,1,si,si,0.050,14.923002,0
1,93.0,56.92,FABIAN,2,2,Fabian Sanchez,si,si,0.069,27.000000,1
2,100.0,15.00,FABIAN,3,2,2,no,no,0.000,15.738427,0
3,123.0,61.85,FABIAN,2,3,2,si,si,0.130,27.000000,0
4,135.0,89.80,FABIAN,4,3,2,si,no,0.000,39.567000,1

# <FONT SIZE=5 COLOR="green"> 3. Revisar donde hay cierto elemento </FONT>

Supongamos que queremos saber las posiciones donde el precio es de 120 millones.

Para saber una determinada posición usamos la instrucción

$$np.where(condicion)$$

In [33]:
# para revisar las posiciones
np.where(aptos["precio"] == 120)

(array([ 27, 362, 363, 364, 365, 366, 528, 529]),)

In [34]:
# para ver las filas
aptos.iloc[[ 27, 362, 363, 364, 365, 366, 528, 529]]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
27,120.0,57.0,occidente,3,2,2,no,no,0.000,68.302000,si
362,120.0,60.0,aburra sur,3,3,2,si,no,0.000,121.000000,si
363,120.0,58.0,aburra sur,3,3,2,no,si,0.125,52.633209,si
364,120.0,60.0,aburra sur,3,2,2,si,no,0.000,44.469049,si
365,120.0,80.0,aburra sur,3,2,1,si,no,0.000,31.083971,si
366,120.0,60.0,aburra sur,3,3,1,no,no,0.092,28.684288,si
528,120.0,58.0,belen guayabal,3,3,2,no,si,0.067,90.000000,si
529,120.0,117.0,belen guayabal,3,4,1,si,no,0.000,61.099000,no

In [35]:
# también se puede con un filtro
aptos[aptos["precio"] == 120]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
27,120.0,57.0,occidente,3,2,2,no,no,0.000,68.302000,si
362,120.0,60.0,aburra sur,3,3,2,si,no,0.000,121.000000,si
363,120.0,58.0,aburra sur,3,3,2,no,si,0.125,52.633209,si
364,120.0,60.0,aburra sur,3,2,2,si,no,0.000,44.469049,si
365,120.0,80.0,aburra sur,3,2,1,si,no,0.000,31.083971,si
366,120.0,60.0,aburra sur,3,3,1,no,no,0.092,28.684288,si
528,120.0,58.0,belen guayabal,3,3,2,no,si,0.067,90.000000,si
529,120.0,117.0,belen guayabal,3,4,1,si,no,0.000,61.099000,no

In [36]:
# cuántos apartamentos tienen precio de 120 millones
sum(aptos["precio"] == 120)

8

# <FONT SIZE=5 COLOR="green"> 4. Ejemplo </FONT>

En el siguiente ejemplo mostraremos algunos elementos de exploración de datos y además algunas funciones importantes.

In [ ]:
na_values=" "

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# cargamos los datos crédito
credito = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/credict_para_limpiar.csv")
credito.head()

,Trajeta,Reportes Negativos,Edad,Ingreso,Proporcion de Gasto,Gasto,Propietario de Vivienda,Trabajor Independiente,Dependientes,Meses de Historial,Tarjetas Principales,Cuentas Activas
0,yes,0,37.66667,4.5200,0.033270,124.983300,yes,no,3,54,1,12.0
1,yes,0,33.25,2.4200,0.005217,9.854167,no,no,3,34,1,13.0
2,yes,0,33.66667,4.5000,0.004156,15.000000,yes,no,4,5o,1,5.0
3,yes,0,30.5,2.5400,0.065214,137.869200,no,no,0,25,1,7.0
4,yes,0,32.16667,9.7867,0.067051,546.503300,yes,no,2,64,1,5.0

In [ ]:
credito.head()

,Trajeta,Reportes Negativos,Edad,Ingreso,Proporcion de Gasto,Gasto,Propietario de Vivienda,Trabajor Independiente,Dependientes,Meses de Historial,Tarjetas Principales,Cuentas Activas
0,yes,0,37.66667,4.5200,0.033270,124.983300,yes,no,3,54,1,12.0
1,yes,0,33.25,2.4200,0.005217,9.854167,no,no,3,34,1,13.0
2,yes,0,33.66667,4.5000,0.004156,15.000000,yes,no,4,5o,1,5.0
3,yes,0,30.5,2.5400,0.065214,137.869200,no,no,0,25,1,7.0
4,yes,0,32.16667,9.7867,0.067051,546.503300,yes,no,2,64,1,5.0

In [ ]:
credito.tail()

,Trajeta,Reportes Negativos,Edad,Ingreso,Proporcion de Gasto,Gasto,Propietario de Vivienda,Trabajor Independiente,Dependientes,Meses de Historial,Tarjetas Principales,Cuentas Activas
1314,yes,0,33.58333,4.566,0.002146,7.333333,yes,no,0,94,1,19.0
1315,no,5,23.91667,3.192,0.000376,0.000000,no,no,3,12,1,5.0
1316,yes,0,40.58333,4.600,0.026513,101.298300,yes,no,2,1,1,2.0
1317,yes,0,32.83333,3.700,0.008999,26.996670,no,yes,0,60,1,7.0
1318,yes,0,48.25,3.700,0.111619,344.157500,yes,no,2,2,1,0.0

In [ ]:
credito.shape

(1319, 12)

In [ ]:
credito.columns

Index(['Trajeta', 'Reportes Negativos', 'Edad', 'Ingreso',
       'Proporcion de Gasto', 'Gasto', 'Propietario de Vivienda',
       'Trabajor Independiente', 'Dependientes', 'Meses de Historial',
       'Tarjetas Principales', 'Cuentas Activas'],
      dtype='object')

In [ ]:
credito.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Trajeta                  1319 non-null   object
 1   Reportes Negativos       1319 non-null   int64
 2   Edad                     1317 non-null   object
 3   Ingreso                  1318 non-null   float64
 4   Proporcion de Gasto      1318 non-null   float64
 5   Gasto                    1319 non-null   float64
 6   Propietario de Vivienda  1318 non-null   object
 7   Trabajor Independiente   1317 non-null   object
 8   Dependientes             1319 non-null   int64
 9   Meses de Historial       1314 non-null   object
 10  Tarjetas Principales     1319 non-null   int64
 11  Cuentas Activas          1318 non-null   float64
dtypes: float64(4), int64(3), object(5)
memory usage: 123.8+ KB

In [ ]:
credito.describe()

,Reportes Negativos,Ingreso,Proporcion de Gasto,Gasto,Dependientes,Tarjetas Principales,Cuentas Activas
count,1319.000000,1318.000000,1318.000000,1319.000000,1319.000000,1319.000000,1318.000000
mean,0.456406,3.360342,0.076440,185.057071,0.993935,0.817286,7.002276
std,1.345267,1.684647,0.186243,272.218917,1.247745,0.386579,6.305256
min,0.000000,0.210000,0.000109,0.000000,0.000000,0.000000,0.000000
25%,0.000000,2.240625,0.002409,4.583333,0.000000,1.000000,2.000000
50%,0.000000,2.900000,0.039175,101.298300,1.000000,1.000000,6.000000
75%,0.000000,4.000000,0.094029,249.035800,2.000000,1.000000,11.000000
max,14.000000,13.500000,3.890000,3099.505000,6.000000,1.000000,46.000000

In [ ]:
credito.describe(include="object")

,Trajeta,Edad,Propietario de Vivienda,Trabajor Independiente,Meses de Historial
count,1319,1317,1318,1317,1314
unique,4,422,4,2,196
top,yes,28.16667,no,no,12
freq,1017,13,737,1226,99

In [ ]:
credito.Trajeta.value_counts()

Trajeta
yes    1017
no      293
Yes       6
No        3
Name: count, dtype: int64

**Contexto de los datos**

Este conjunto de datos contiene información financiera y demográfica de individuos relacionada con el uso y posesión de tarjetas de crédito. El objetivo principal es analizar los factores asociados a la tenencia de una tarjeta de crédito y estudiar el comportamiento financiero de los clientes.

Las variables incluyen características personales (edad, ingresos, número de dependientes), características laborales (trabajador independiente o no), situación patrimonial (propietario de vivienda) e información crediticia (historial de reportes negativos, número de tarjetas y cuentas activas).

Este conjunto de datos es ampliamente utilizado en cursos de estadística, minería de datos y aprendizaje automático para ilustrar técnicas de análisis exploratorio, filtrado de datos, agrupamiento (`groupby`), visualización y modelos de clasificación.

La variable de mayor interés suele ser `card`, que indica si una persona posee o no una tarjeta de crédito. A partir de las demás variables, es posible identificar patrones que ayuden a explicar o predecir dicha condición.


| Variable | Traducción | Descripción |
|-----------|------------|-------------|
| `card` | Tarjeta | Indica si la persona posee una tarjeta de crédito (sí/no). |
| `reports` | Reportes negativos | Número de reportes negativos o incidentes en el historial crediticio. |
| `age` | Edad | Edad de la persona (años). |
| `income` | Ingreso | Ingreso anual del individuo o hogar. |
| `share` | Proporción de gasto | Proporción del ingreso destinada a gastos con tarjeta. |
| `expenditure` | Gasto | Gasto mensual realizado con tarjeta de crédito. |
| `owner` | Propietario de vivienda | Indica si posee vivienda propia (sí/no). |
| `selfemp` | Trabajador independiente | Indica si es trabajador independiente o autónomo (sí/no). |
| `dependents` | Dependientes | Número de personas dependientes económicamente. |
| `months` | Meses de historial | Meses de historial crediticio o de permanencia en el sistema financiero. |
| `majorcards` | Tarjetas principales | Número de tarjetas de crédito principales que posee. |
| `active` | Cuentas activas | Número de cuentas de crédito activas. |

In [ ]:
credito.isna().sum()

Trajeta                    0
Reportes Negativos         0
Edad                       2
Ingreso                    1
Proporcion de Gasto        1
Gasto                      0
Propietario de Vivienda    1
Trabajor Independiente     2
Dependientes               0
Meses de Historial         5
Tarjetas Principales       0
Cuentas Activas            1
dtype: int64

**Ejercicio**

**Parte 1**

- Exploración rápida de los datos

- Existen variables inconsistentes

- Hay datos faltantes

- Cambiar el nombre de la primera columna

- Eliminar la variable "reportes negativo"

- Arregle las inconsistencias

  - Si hay datos como "4o" podríamos salvarlos cambiando a 40
  
  - En este caso vamos a eliminar los datos faltantes

  - Unificar, si es necesario categorias

  - Eliminar datos que no son válidos en el contexto

**Parte 2**

- Analice las estadísticas de la variable **Edad**.

- Haga la tabla de frecuencia de la variable **Tarjeta** y de **Propietario de Vivienda**

- Ahora, haga la tabla cruzada de las variables anteriores.

- ¿Cuál es el promedio de **edad** por **propietario de vivienda**?

- Calcule las estadísticas descriptivas del **Gasto** dependiendo del número de dependientes.

**Parte 3**

- ¿Cuántas personas tienen 3 dependientes?

- ¿Cuántas personas son propietarios de vivienda y tienen más de 30 meses de historial?

- ¿Cuántas personas gastan menos de 200 us, no tienen vivienda propia y están entre 30 y 50 años?

- ¿Cuántas personas tienen más (o igual) de 6 cuentas activas y fue negada la tarjeta de crédito?

**Solución**

**Coerción**

La coerción es el proceso mediante el cual un lenguaje o una función convierte automáticamente un dato de un tipo a otro para poder realizar una operación.

In [ ]:
# ejemplo de coerción
pd.to_numeric(credito.Edad, errors='coerce')

In [ ]:
# identificamos donde hay errores
pd.to_numeric(credito.Edad, errors='coerce').isna()

In [ ]:
# identificamos las posiciones
np.where(pd.to_numeric(credito.Edad, errors='coerce').isna())

In [ ]:
# vamos a hacer coherción de datos: forzar a que se convierta en uno u otro tipo
credito.iloc[[ 11,  15, 116, 569]]

**veamos otra variable**

In [ ]:
credito.info()

In [ ]:
# revisar cadenas de texto en months
credito["months"].unique()

In [ ]:
pd.to_numeric(credito.months, errors='coerce').isna()

In [ ]:
sum(pd.to_numeric(credito.months, errors='coerce').isna())

In [ ]:
np.where(pd.to_numeric(credito.months, errors='coerce').isna())[0]

In [ ]:
credito.iloc[list(np.where(pd.to_numeric(credito.months, errors='coerce').isna())[0])]

**Para pensar un poco (siguiente tema-martes)**

In [ ]:
# función para detectar
def problema_texto(datos, x):
  u = pd.to_numeric(datos[x], errors='coerce').isna()
  posiciones = np.where(u)[0]
  print(posiciones)
  return datos.iloc[posiciones]

In [ ]:
problema_texto(credito, "age")