<table>
        <td>
        <td><img src="https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/logo_ECI.png" width="400"/></td>
        <td>&nbsp;</td>
        <td>
            <h1 style="font-size:200%;color:blue;text-align:center">    <FONT COLOR="blue"> DataFrames </p> Parte 2: Manipulación  </FONT>         </h1></td>         
        <td>
            <tp><p style="font-size:99%;text-align:center">Diplomado Ciencia de Datos </p></tp>
            <tp><p style="font-size:115%;text-align:center">2026-1</p></tp>
            <tp><p style="font-size:115%;text-align:center">Prof. Fabián Sánchez</p></tp>
        </td>
    </tr>
</table>

# <FONT SIZE=5 COLOR="red"> Contenidos del Notebook </FONT>

En este notebook encontrará:

- Manipulación de DataFrames

  + Ordenar por una variable
  + Renombrar una variable
  + Eliminar variables
  + Agregar una variable
  + Agrupaciones

- Filtros en el DataFrame

# <FONT SIZE=5 COLOR="green"> 1. Manipulación de DataFrame </FONT>

En esta sección revisaremos algunas operaciones y acciones que son importantes de conocer en un Data.Frame:

- Ordenar por una variable

- Renombrar una variable

- Eliminar una variable

- Agregar una variable

- Agrupar por categorias de una variable y aplicar funciones.

Para repasar

https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

In [1]:
# librerías de trabajo
import pandas as pd
import numpy as np

In [2]:
aptos = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/master/apartamentos.csv")
aptos.head()

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,1,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,2,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,3,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,4,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,5,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [3]:
homicidios = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/homicidios.csv")
homicidios.head()

,Fecha,Departamento,Municipio,Día,Hora,Barrio,Zona,Clase de sitio,Arma empleada,Móvil Agresor,Móvil Victima,Edad,Sexo,Estado civil,País de nacimiento,Clase de empleado,Profesión,Escolaridad,Código DANE,Cantidad
0,1/1/2017,AMAZONAS,LETICIA (CT),Domingo,15:05:00,KILOMETRO 11,RURAL,CARRETERA,ARMA BLANCA / CORTOPUNZANTE,PASAJERO MOTOCICLETA,PASAJERO MOTOCICLETA,20,MASCULINO,SOLTERO,COLOMBIA,EMPLEADO PARTICULAR,-,SECUNDARIA,"91,001,000",1
1,1/1/2017,ANTIOQUIA,BETANIA,Domingo,21:20:00,LA CUMBRE,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,A PIE,A PIE,21,MASCULINO,SOLTERO,COLOMBIA,INDEPENDIENTE,-,PRIMARIA,"5,091,000",1
2,1/1/2017,ANTIOQUIA,COPACABANA,Domingo,4:48:00,MACHADO,URBANA,DENTRO DE LA VIVIENDA,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,22,MASCULINO,UNION LIBRE,COLOMBIA,INDEPENDIENTE,-,SECUNDARIA,"5,212,000",1
3,1/1/2017,ANTIOQUIA,EBÉJICO,Domingo,5:00:00,SAGUA,RURAL,FINCAS Y SIMILARES,ARMA DE FUEGO,A PIE,A PIE,46,MASCULINO,SOLTERO,COLOMBIA,INDEPENDIENTE,-,SECUNDARIA,"5,240,000",1
4,1/1/2017,ANTIOQUIA,EL BAGRE,Domingo,6:30:00,LAS BRISAS,URBANA,VIAS PUBLICAS,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,37,MASCULINO,UNION LIBRE,COLOMBIA,INDEPENDIENTE,-,PRIMARIA,"5,250,000",1

## <FONT SIZE=4 COLOR="magenta"> 1.1 Ordenar según una variable </FONT>

Para ordenar por una variable usamos la instrucción

$$datos.sort\_values(variable, ascending = False) $$

se usa:

- *ascending=True* :  ordena de menor a mayor. (default)
- *ascending=False* : ordena de mayor a menor.

In [4]:
# ordenamos por la variable precio de mayor a menor
aptos.sort_values("precio" , ascending =  False)

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
346,347,1700.0,399.00,poblado,6,3,3,no,si,0.9340,701.731,si
345,346,1490.0,445.00,poblado,6,5,4,si,si,0.7490,701.731,si
344,345,1450.0,238.19,poblado,6,4,4,si,si,0.8286,675.072,si
343,344,1450.0,318.00,poblado,6,3,3,si,si,0.7490,611.027,si
342,343,1430.0,291.00,poblado,6,3,3,si,si,0.7490,701.731,si
...,...,...,...,...,...,...,...,...,...,...,...,...
348,349,63.0,43.00,aburra sur,3,3,1,no,no,0.0500,41.468,si
11,12,53.0,37.56,occidente,3,3,1,no,si,0.0000,16.486,si
10,11,47.0,43.00,occidente,2,2,1,no,no,0.0000,16.486,no
347,348,45.0,53.00,aburra sur,3,3,1,si,no,0.0000,23.899,si
644,645,25.0,118.00,laureles,5,3,2,si,no,0.0000,95.885,si

In [5]:
# ordenamos por la variable precio de menor a mayor
aptos.sort_values("precio" , ascending =  True)

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
644,645,25.0,118.00,laureles,5,3,2,si,no,0.0000,95.885,si
347,348,45.0,53.00,aburra sur,3,3,1,si,no,0.0000,23.899,si
10,11,47.0,43.00,occidente,2,2,1,no,no,0.0000,16.486,no
11,12,53.0,37.56,occidente,3,3,1,no,si,0.0000,16.486,si
348,349,63.0,43.00,aburra sur,3,3,1,no,no,0.0500,41.468,si
...,...,...,...,...,...,...,...,...,...,...,...,...
342,343,1430.0,291.00,poblado,6,3,3,si,si,0.7490,701.731,si
344,345,1450.0,238.19,poblado,6,4,4,si,si,0.8286,675.072,si
343,344,1450.0,318.00,poblado,6,3,3,si,si,0.7490,611.027,si
345,346,1490.0,445.00,poblado,6,5,4,si,si,0.7490,701.731,si
346,347,1700.0,399.00,poblado,6,3,3,no,si,0.9340,701.731,si

In [6]:
# default ordena de menor a mayor por la variable ubicación
# lo hace por orden alfabético
aptos.sort_values("ubicacion", ascending = True)

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
419,420,175.0,65.00,aburra sur,3,3,2,si,si,0.154,46.291597,si
457,458,220.0,72.00,aburra sur,4,2,2,si,si,0.211,96.390800,si
458,459,220.0,73.00,aburra sur,4,3,2,si,si,0.000,96.390800,si
459,460,220.0,89.00,aburra sur,5,3,2,no,si,0.000,143.000000,si
460,461,225.0,100.00,aburra sur,3,4,3,si,si,2.280,108.600000,si
...,...,...,...,...,...,...,...,...,...,...,...,...
232,233,445.0,129.63,poblado,6,3,4,si,si,0.350,309.352000,no
233,234,445.0,95.57,poblado,6,2,2,si,si,0.328,234.140000,si
234,235,448.5,108.00,poblado,6,3,2,si,si,0.380,252.426000,si
226,227,440.0,151.34,poblado,6,5,4,no,si,0.350,247.900000,si
346,347,1700.0,399.00,poblado,6,3,3,no,si,0.934,701.731000,si

In [7]:
aptos.columns

Index(['Unnamed: 0', 'precio', 'mt2', 'ubicacion', 'estrato', 'alcobas',
       'banos', 'balcon', 'parqueadero', 'administracion', 'avaluo',
       'terminado'],
      dtype='object')

## <FONT SIZE=4 COLOR="magenta"> 1.2 Renombrar una variable </FONT>

Podemos renombrar una columna de la siguiente forma usando la instrucción ***rename***

$$ datos.rename(columns=\{key : value, key : value\}, inplace=True) $$

 - Para cambiar el nombre de una variable debemos usar un diccionario donde las claves son las variables actuales y los valores son los nombres nuevos de las variables.
 - Recordemos que la instrucción **inplace** se usa para determinar si cambiamos el DataFrame original.

In [8]:
# es recomendable hacer una copia
aptos2 = aptos.copy()

In [9]:
# cambiaremos el nombre de administracion por admon
aptos2.rename(columns={"administracion" : "admon"}, inplace = True)

In [10]:
# ahora sí quedó sobre datos2.
aptos2.head()

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,admon,avaluo,terminado
0,1,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,2,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,3,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,4,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,5,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [11]:
# ejemplo
homicidios.columns

Index(['Fecha', 'Departamento', 'Municipio', 'Día', 'Hora', 'Barrio', 'Zona',
       'Clase de sitio', 'Arma empleada', 'Móvil Agresor', 'Móvil Victima',
       'Edad', 'Sexo', 'Estado civil', 'País de nacimiento',
       'Clase de empleado', 'Profesión', 'Escolaridad', 'Código DANE',
       'Cantidad'],
      dtype='object')

In [12]:
# cambiar Estado civil por e.civil y Móvil Victima por m.victima
homicidios2 = homicidios.copy()
homicidios2.rename(columns={"Estado civil" : "e.civil" , "Móvil Victima" : "m.victima"}, inplace = True)

In [13]:
homicidios2.columns

Index(['Fecha', 'Departamento', 'Municipio', 'Día', 'Hora', 'Barrio', 'Zona',
       'Clase de sitio', 'Arma empleada', 'Móvil Agresor', 'm.victima', 'Edad',
       'Sexo', 'e.civil', 'País de nacimiento', 'Clase de empleado',
       'Profesión', 'Escolaridad', 'Código DANE', 'Cantidad'],
      dtype='object')

## <FONT SIZE=4 COLOR="magenta"> 1.3 Eliminar filas y columnas</FONT>

Para eliminar una columna o una fila usamos la instrucción .drop

$$datos.drop(``nombre", axis = 1, inplace = T \, or \, F)$$

- *axis = 1* : es por columna
- *axis = 0* : es por  fila
- *inplace = T* : sobreescribe en el *df* original.
- *inplace = F* : no sobreescribe. Mantiene el original

In [14]:
aptos2.head()

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,admon,avaluo,terminado
0,1,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,2,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,3,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,4,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,5,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [15]:
# Eliminar la variable "Unnamed: 0"
aptos2.drop("Unnamed: 0", axis = 1 , inplace = True)

In [16]:
aptos2.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,admon,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [17]:
homicidios2.columns

Index(['Fecha', 'Departamento', 'Municipio', 'Día', 'Hora', 'Barrio', 'Zona',
       'Clase de sitio', 'Arma empleada', 'Móvil Agresor', 'm.victima', 'Edad',
       'Sexo', 'e.civil', 'País de nacimiento', 'Clase de empleado',
       'Profesión', 'Escolaridad', 'Código DANE', 'Cantidad'],
      dtype='object')

In [18]:
homicidios2.head()

,Fecha,Departamento,Municipio,Día,Hora,Barrio,Zona,Clase de sitio,Arma empleada,Móvil Agresor,m.victima,Edad,Sexo,e.civil,País de nacimiento,Clase de empleado,Profesión,Escolaridad,Código DANE,Cantidad
0,1/1/2017,AMAZONAS,LETICIA (CT),Domingo,15:05:00,KILOMETRO 11,RURAL,CARRETERA,ARMA BLANCA / CORTOPUNZANTE,PASAJERO MOTOCICLETA,PASAJERO MOTOCICLETA,20,MASCULINO,SOLTERO,COLOMBIA,EMPLEADO PARTICULAR,-,SECUNDARIA,"91,001,000",1
1,1/1/2017,ANTIOQUIA,BETANIA,Domingo,21:20:00,LA CUMBRE,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,A PIE,A PIE,21,MASCULINO,SOLTERO,COLOMBIA,INDEPENDIENTE,-,PRIMARIA,"5,091,000",1
2,1/1/2017,ANTIOQUIA,COPACABANA,Domingo,4:48:00,MACHADO,URBANA,DENTRO DE LA VIVIENDA,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,22,MASCULINO,UNION LIBRE,COLOMBIA,INDEPENDIENTE,-,SECUNDARIA,"5,212,000",1
3,1/1/2017,ANTIOQUIA,EBÉJICO,Domingo,5:00:00,SAGUA,RURAL,FINCAS Y SIMILARES,ARMA DE FUEGO,A PIE,A PIE,46,MASCULINO,SOLTERO,COLOMBIA,INDEPENDIENTE,-,SECUNDARIA,"5,240,000",1
4,1/1/2017,ANTIOQUIA,EL BAGRE,Domingo,6:30:00,LAS BRISAS,URBANA,VIAS PUBLICAS,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,37,MASCULINO,UNION LIBRE,COLOMBIA,INDEPENDIENTE,-,PRIMARIA,"5,250,000",1

In [19]:
aptos.columns

Index(['Unnamed: 0', 'precio', 'mt2', 'ubicacion', 'estrato', 'alcobas',
       'banos', 'balcon', 'parqueadero', 'administracion', 'avaluo',
       'terminado'],
      dtype='object')

In [20]:
aptos2.drop([4,6], axis =0)

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,admon,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
5,140.0,71.00,norte,3,3,2,no,si,0.120,31.145508,si
...,...,...,...,...,...,...,...,...,...,...,...
689,498.0,180.00,laureles,5,4,3,si,si,0.570,233.784000,si
690,508.0,209.00,laureles,6,4,3,si,si,0.450,258.850000,si
691,550.0,149.00,laureles,6,3,4,no,si,0.747,326.157000,si
692,630.0,179.00,laureles,5,3,3,si,si,0.340,324.114000,si
693,1350.0,494.00,laureles,5,3,4,si,si,1.600,320.000000,si

In [ ]:
aptos2.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,admon,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

## <FONT SIZE=4 COLOR="magenta"> 1.4 Agregar una variable </FONT>

Para agregar una variable usamos la instrucción

$$datos[``\text{nueva variable}"] = lista $$

In [21]:
aptos2.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,admon,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [22]:
# agregar la variable "precio/mt2"
aptos2["nueva"] = aptos2.precio/aptos2.mt2

In [23]:
aptos2.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,admon,avaluo,terminado,nueva
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no,1.830399
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si,1.633872
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no,1.506024
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no,1.988682
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si,1.503341

## <FONT SIZE=4 COLOR="magenta"> 1.5 Agrupaciones: ***groupby()*** </FONT>

Podemos hacer operaciones con las agrupaciones, así:

$$datos.groupby(``Variable")[``\text{segunda variable}"].funcion()$$

Por ejemplo, supongamos que queremos agrupar por escolaridad y calcular el promedio de las edades de cada uno de los grupos.

<center><img src="https://github.com/Fabian830348/cursos/blob/master/intro/groupby.png?raw=true" alt="centered image" width="450" height="350"></center> <center><figcaption> <FONT SIZE=1 COLOR="black"> Fuente: Elaboración propia  </FONT> <figcaption></center>

In [24]:
aptos2.groupby("ubicacion")

In [25]:
# calcula la media del precio en cada ubicación
aptos2.groupby("ubicacion")["precio"].mean()

ubicacion
aburra sur        193.672781
belen guayabal    168.865672
centro            130.815789
laureles          318.520548
norte             131.000000
occidente         164.304348
poblado           506.017317
Name: precio, dtype: float64

In [26]:
# calcular las estadísticas del precio en cada ubicación
aptos2.groupby("ubicacion")["precio"].describe()

,count,mean,std,min,25%,50%,75%,max
ubicacion,,,,,,,,
aburra sur,169.0,193.672781,64.570992,45.0,140.00,185.0,250.00,330.0
belen guayabal,67.0,168.865672,50.277983,75.0,140.00,165.0,210.00,265.0
centro,38.0,130.815789,50.874438,67.0,87.00,128.0,149.25,260.0
laureles,73.0,318.520548,159.220594,25.0,235.00,290.0,370.00,1350.0
norte,10.0,131.000000,31.770007,79.0,105.75,137.5,156.25,175.0
occidente,69.0,164.304348,59.968694,47.0,120.00,160.0,210.00,320.0
poblado,268.0,506.017317,290.683116,140.0,320.00,415.0,605.00,1700.0

In [27]:
aptos2.parqueadero.unique()

array(['si', 'no'], dtype=object)

In [28]:
# si agrupamos por ubicacion, y parqueadero quiero saber el valor máximo del precio
aptos2.groupby(["ubicacion" , "parqueadero"]).precio.max()

ubicacion       parqueadero
aburra sur      no              220.0
                si              330.0
belen guayabal  no              265.0
                si              260.0
centro          no              260.0
                si              210.0
laureles        no              190.0
                si             1350.0
norte           no              160.0
                si              175.0
occidente       no              320.0
                si              270.0
poblado         no              190.0
                si             1700.0
Name: precio, dtype: float64

In [29]:
aptos.groupby(["ubicacion", "parqueadero"]).precio.min()

ubicacion       parqueadero
aburra sur      no              45.0
                si             112.0
belen guayabal  no              75.0
                si              86.0
centro          no              67.0
                si              70.0
laureles        no              25.0
                si             140.0
norte           no             100.0
                si              79.0
occidente       no              47.0
                si              53.0
poblado         no             170.0
                si             140.0
Name: precio, dtype: float64

# <FONT SIZE=5 COLOR="green"> 2. Filtros en un DataFrame </FONT>

En esta sección revisaremos algunos filtros en un dataframe. Para esto, generaremos algunas preguntas y buscaremos responderlas con los filtros.

De esta manera podemos seguir haciendo filtros y respondiendo algunas preguntas. Se debe tener en cuenta:

- Operadores de comparación :

    - **>** : mayor que
    - **<** : menor que
    - **>=**  : mayor o igual
    - **<=** : menor o igual
    - **!=** (diferente)

- Operadores lógicos:

    - **&**  : y
    - **|**  : o

<FONT SIZE=3 COLOR="blue"> Pregunta 1: ¿Cuántos apartamentos tienen precio mayor a 100 millones? </FONT>

In [31]:
aptos2.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,admon,avaluo,terminado,nueva
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no,1.830399
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si,1.633872
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no,1.506024
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no,1.988682
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si,1.503341

In [45]:
sum(aptos2.precio > 400)

147

In [32]:
# apartamentos de mas de 400 millones
aptos2[aptos2.precio > 400]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,admon,avaluo,terminado,nueva
210,410.0,220.00,poblado,6,3,3,si,si,0.795,400.805,si,1.863636
211,410.0,168.50,poblado,6,3,3,no,si,0.536,277.500,no,2.433234
212,410.0,132.98,poblado,6,4,3,si,si,0.800,369.977,si,3.083170
213,420.0,197.00,poblado,6,3,3,si,si,0.545,263.615,si,2.131980
214,420.0,163.00,poblado,6,3,3,si,si,0.360,227.471,si,2.576687
...,...,...,...,...,...,...,...,...,...,...,...,...
689,498.0,180.00,laureles,5,4,3,si,si,0.570,233.784,si,2.766667
690,508.0,209.00,laureles,6,4,3,si,si,0.450,258.850,si,2.430622
691,550.0,149.00,laureles,6,3,4,no,si,0.747,326.157,si,3.691275
692,630.0,179.00,laureles,5,3,3,si,si,0.340,324.114,si,3.519553
693,1350.0,494.00,laureles,5,3,4,si,si,1.600,320.000,si,2.732794

In [38]:
# cuántos apartamentos de mas de 400 millones
len(aptos2[aptos2.precio > 400])

147

<FONT SIZE=3 COLOR="blue"> Pregunta 2: ¿Cuántos apartamentos del poblado tienen precio mayor a 200 millones? </FONT>

In [ ]:
aptos2[(aptos2["precio"]==420) & (aptos2["ubicacion"] == "poblado")]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,admon,avaluo,terminado,nueva
213,420.0,197.0,poblado,6,3,3,si,si,0.5450,263.615,si,2.131980
214,420.0,163.0,poblado,6,3,3,si,si,0.3600,227.471,si,2.576687
215,420.0,100.0,poblado,6,2,2,no,si,0.4539,418.238,si,4.200000
216,420.0,151.0,poblado,6,3,3,no,si,0.5780,237.166,si,2.781457

In [39]:
len(aptos2[(aptos2["precio"]==420) & (aptos2["ubicacion"] == "poblado")])

4

<FONT SIZE=3 COLOR="blue"> Pregunta 3: ¿Cuántos apartamentos del sector laureles, tienen más de 50 metros cuadrados y no cuentan con parqueadero? </FONT>

In [43]:
len(aptos2[(aptos2["mt2"]>50) & (aptos2["ubicacion"]=="laureles") & (aptos2["parqueadero"]=="no")])

3